---
permalink: a900/controller_replace_recable_reassign_disks.html
sidebar: sidebar
keywords:
summary:
---
= Recable the system - AFF A900
:icons: font
:imagesdir: ../media/

[.lead]
Continue the replacement procedure by recabling the storage and network conigurations.

== Step 1: Recable the system

After running diagnostics, you must recable the controller module's storage and network connections.

.Steps
. Recable the system.
. Verify that the cabling is correct by using https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor].
.. Download and install Config Advisor.
.. Enter the information for the target system, and then click Collect Data.
.. Click the Cabling tab, and then examine the output. Make sure that all disk shelves are displayed and all disks appear in the output, correcting any cabling issues you find.
.. Check other cabling by clicking the appropriate tab, and then examining the output from Config Advisor.

NOTE: The system ID and  disk assignment information reside in the NVRAM module, which is in a module separate from the controller module and not impacted by the controller module replacement.
