---
permalink: a200/bootmedia-replace-overview.html
sidebar: sidebar
keywords: aff, a200, aff a200, boot, media, store, primary, secondary, set, system, image, file, network, configuration, nondisruptive, disruptive, replacement, replace, replace the boot media
summary: The boot media stores a primary and secondary set of system \(boot image\) files that the system uses when it boots. Depending on your network configuration, you can perform either a nondisruptive or disruptive replacement.
---
= Replace the boot media - AFF A200
:icons: font
:imagesdir: ../media/

[.lead]
The boot media stores a primary and secondary set of system (boot image) files that the system uses when it boots. Depending on your network configuration, you can perform either a nondisruptive or disruptive replacement.

.What you'll need

You must have a USB flash drive, formatted to FAT32, with the appropriate amount of storage to hold the `image_xxx.tgz`.

.Before you begin
* The nondisruptive and disruptive methods for replacing a boot media both require you to restore the var file system:
 ** For nondisruptive replacement, the HA pair must be connected to a network to restore the var file system.
 ** For disruptive replacement, you do not need a network connection to restore the var file system, but the process requires two reboots.
* You must replace the failed component with a replacement FRU component you received from your provider.
* It is important that you apply the commands in these steps on the correct node:
 ** The _impaired node_ is the node on which you are performing maintenance.
 ** The _healhy node_ is the HA partner of the impaired node.
