---
sidebar: sidebar.html
permalink: task_shutdown.html
keywords: AFF, FAS
summary: Shutting down
---

= Shutting down the impaired node
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To shut down the impaired node, you must determine the status of the node and, if necessary, take over the node so that the healthy node continues to serve data from the impaired node storage.

== Before you begin

* If you have a cluster with more than two nodes, it must be in quorum. If the cluster is not in quorum or a healthy node shows false for eligibility and health, you must correct the issue before shutting down the impaired node.
+ONTAP 9 System Administration Reference

* If you are using NetApp Storage Encryption, you must have reset the MSID using the instructions in the "Returning SEDs to unprotected mode" section of the ONTAP 9 NetApp Encryption Power Guide.
+ONTAP 9 NetApp Encryption Power Guide

* If you have a SAN system, you must have checked event messages (event log show) for impaired node SCSI blade.
* Each SCSI-blade process should be in quorum with the other nodes in the cluster. Any issues must be resolved before you proceed with the replacement.
* If you have a MetroCluster configuration, you must have confirmed that the MetroCluster Configuration State is configured and that the nodes are in an enabled and normal state (metrocluster node show).

. Steps

. If the impaired node is part of an HA pair, disable automatic giveback from the console of the healthy node: storage failover modify -node local -auto-giveback false

. Take the impaired node to the LOADER prompt:

[cols=2*,options="header",cols="40,60"]
|===
| If the impaired system is displaying...
| Then...
| The LOADER prompt  | Go to the next step.
| Waiting for giveback... | Press Ctrl-C, and then respond y.
| System prompt or password prompt (enter system password) | Take over or halt the impaired node: storage failover takeover -ofnode impaired_node_name
|===
