---
permalink: platform-supplemental/drive-hotswap-drive.html
sidebar: sidebar
keywords: drive, fail, platform, log, warning, message, system, console, drive, addition, fault, led, operator, display, panel, fault, led, illuminate, nondisruptive, i/o, hot-swap, hot-swap a drive
summary: When a drive fails, the platform logs a warning message to the system console indicating which drive has failed. In addition, both the fault LED on the operator display panel and the fault LED on the failed drive are illuminated. You can replace a failed drive nondisruptively while I/O is in progress.
---
= Hot-swap a drive
:icons: font
:imagesdir: ../media/

[.lead]
When a drive fails, the platform logs a warning message to the system console indicating which drive has failed. In addition, both the fault LED on the operator display panel and the fault LED on the failed drive are illuminated. You can replace a failed drive nondisruptively while I/O is in progress.

* The replacement drive must be supported by your platform.
+
https://hwu.netapp.com[NetApp Hardware Universe]

* If SED authentication is enabled, you must use the SED replacement instructions in the ONTAP documentation.
+
Instructions in the ONTAP documentation describe additional steps you must perform before and after replacing an SED.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html[ONTAP 9 NetApp Encryption Power Guide]

* All other components in the system must be functioning properly; if not, contact technical support.
* Verify the drive you are removing is failed by running the `storage disk show -broken` command. The failed drive appears in the list of failed drives. If it does not, you should wait, and then run the command again.
+
NOTE: Depending on the drive type and capacity, it can take up to several hours for the drive to appear in the list of failed drives.

* *Best practice:* The best practice is to have the current version of the Disk Qualification Package (DQP) installed before hot-swapping a drive.
* Drive firmware is automatically updated (nondisruptively) on new drives that have non current firmware versions.
* When you unpack the replacement drive, save all packing materials for use when you return the failed drive.

. If you want to manually assign drive ownership for the replacement drive, you need to disable automatic drive assignment replacement drive, if it is enabled
+
NOTE: You manually assign drive ownership and then reenable automatic drive assignment later in this procedure.

 .. Verify whether automatic drive assignment is enabled: `storage disk option show`
+
You can enter the command on either controller module.
+
If automatic drive assignment is enabled, the output shows `on` in the "`Auto Assign`" column (for each controller module).

 .. If automatic drive assignment is enabled, disable it: `storage disk option modify -node node_name -autoassign off`
+
You must disable automatic drive assignment on both controller modules.

. Properly ground yourself.
. Physically identify the failed drive.
+
When a drive fails, the system logs a warning message to the system console indicating which drive failed. Additionally, the attention (amber) LED on the drive shelf operator display panel and the failed drive illuminate.
+
NOTE: The activity (green) LED on a failed drive can be illuminated (solid), which indicates that the drive has power, but should not be blinking, which indicates I/O activity. A failed drive has no I/O activity.

. Remove the failed drive:
 .. Press the release button on the drive face to open the cam handle.
 .. Slide the drive out of the shelf using the cam handle and supporting the drive with your other hand.
. Wait a minimum of 70 seconds before inserting the replacement drive.
+
This allows the system to recognize that a drive was removed.

. Insert the replacement drive:
 .. With the cam handle in the open position, use both hands to insert the replacement drive.
 .. Push until the drive stops.
 .. Close the cam handle so that the drive is fully seated into the mid plane and the handle clicks into place.
+
Be sure to close the cam handle slowly so that it aligns correctly with the face of the drive.
. Verify that the drive's activity (green) LED is illuminated.
+
When the drive's activity LED is solid, it means that the drive has power. When the drive's activity LED is blinking, it means that the drive has power and I/O is in progress. If the drive firmware is automatically updating, the LED blinks.

. If you are replacing another drive, repeat Steps 3 through 7.
. If you disabled automatice drive assignment in Step 1, then, manually assign drive ownership and then reenable automatic drive assignment if needed.
 .. Display all unowned drives: `storage disk show -container-type unassigned`
+
You can enter the command on either controller module.

 .. Assign each drive: `storage disk assign -disk disk_name -owner owner_name`
+
You can enter the command on either controller module.
+
You can use the wildcard character to assign more than one drive at once.

 .. Reenable automatic drive assignment if needed: `storage disk option modify -node node_name -autoassign on`
+
You must reenable automatic drive assignment on both controller modules.
. Return the failed part to NetApp, as described in the RMA instructions shipped with the kit.
+
Contact technical support at https://mysupport.netapp.com/site/global/dashboard[NetApp Support], 888-463-8277 (North America), 00-800-44-638277 (Europe), or +800-800-80-800 (Asia/Pacific) if you need the RMA number or additional help with the replacement procedure.
