---
permalink: sas3/overview-cabling-rules-examples.html
sidebar: sidebar
keywords: disk, shelves, shelf, iom12, module, single-controller, configuration, support, platform, sas, cabling, cable, rule, controller, shelf-to-shelf, connection, rule, controller-to-stack, mini-sas, hd, optical, cable, rule, sas cabling rules
summary: The following SAS cabling rules, examples and worksheets are available to help you cable your SAS drive shelves with IOM12 modules to your storage system.
---
= SAS cabling rules, worksheets, and examples overview - shelves with IOM12 modules
:icons: font
:imagesdir: ../media/

[.lead]
The SAS cabling rules, worksheets, and examples content is available to help you cable your SAS drive shelves with IOM12 modules to your storage system.

*SAS cabling rules*

** Configurations
** Controller slot numbering
** Shelf-to-shelf connections
** Controller-to-stack connections
** Mini-SAS HD SAS optical cables

*Cabling worksheets and examples*

** Common multipath HA configurations
** Common AFF A200, AFF A220, FAS2600, and FAS2700 configurations
** Quad-path HA configurations

*Cabling worksheet templates*

** Worksheet templates for multipathed connectivity
** Worksheet template for quad-pathed connectivity
** How to read a worksheet for multipathed connectivity
** How to read a worksheet for quad-pathed connectivity
