---
permalink: a800/bootmedia-encryption-preshutdown-checks.html
sidebar: sidebar
keywords: aff a800, pre-shutdown checks for onboard encryption keys
summary: "Prior to shutting down the impaired controller and checking the status of the onboard encryption keys, you must check the status of the impaired controller, disable automatic giveback, and check what version of ONTAP the system is running."
---
= Check onboard encryption keys - AFF A800
:icons: font
:imagesdir: ../media/

[.lead]
Prior to shutting down the impaired controller and checking the status of the onboard encryption keys, you must check the status of the impaired controller, disable automatic giveback, and check what version of ONTAP the system is running.

include::../_include/encryption_steps_before_shutdown.adoc[]

** If <lno-DARE> is not displayed in the command output, and the system is running ONTAP 9.5, go to <<Checking NVE or NSE on systems running ONTAP 9.5 and later>>.
 ** If <lno-DARE> is not displayed in the command output, and the system is running ONTAP 9.6 or later, go to <<Checking NVE or NSE on systems running ONTAP 9.6 and later>>.

. If the impaired controller is part of an HA configuration, disable automatic giveback from the healthy controller: `storage failover modify -node local -auto-giveback false` or `storage failover modify -node local -auto-giveback-after-panic false`


== Option 1: Check NVE or NSE on systems running ONTAP 9.5 and earlier

include::../_include/encryption_check_95_earlier.adoc[]

== Option 2: Check NVE or NSE on systems running ONTAP 9.6 and later

include::../_include/encryption_check_96_later.adoc[]
