---
permalink: a800/controller-replace-overview.html
sidebar: sidebar
keywords: aff a800, prerequisite, replace the controller module
summary: "You must review the prerequisites for the replacement procedure and select the correct one for your version of the ONTAP operating system."
---
= Replace the controller module - AFF A800
:icons: font
:imagesdir: ../media/

[.lead]
You must review the prerequisites for the replacement procedure and select the correct one for your version of the ONTAP operating system.

* All drive shelves must be working properly.
* The healthy node must be able to take over the node that is being replaced (referred to in this procedure as the "`impaired node`").
* If your system is in a MetroCluster configuration, you must review the section https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html[Choosing the correct recovery procedure] to determine whether you should use this procedure.
* You must replace the failed component with a replacement FRU component you received from your provider.
* You must be replacing a controller module with a controller module of the same model type. You cannot upgrade your system by just replacing the controller module.
* You cannot change any drives or drive shelves as part of this procedure.
* In this procedure, the boot device is moved from the impaired node to the _replacement_ node so that the _replacement_ node will boot up in the same version of ONTAP as the old controller module.
* It is important that you apply the commands in these steps on the correct systems:
 ** The _impaired_ node is the node that is being replaced.
 ** The _replacement node_ is the new node that is replacing the impaired node.
 ** The _healthy node_ is the surviving node.
* You must always capture the node's console output to a text file.
+
This provides you a record of the procedure so that you can troubleshoot any issues that you might encounter during the replacement process.

NOTE: Do not downgrade the BIOS version of the _replacement_ node to match the partner node or the old controller module.
