---
permalink: a250/chassis-replace-complete-system-restore-rma.html
sidebar: sidebar
keywords: aff a250, verify and set HA state, run diagnostics, complete the replacement process
summary: "You must verify the HA state of the chassis, run diagnostics, and return the failed part to NetApp, as described in the RMA instructions shipped with the kit."
---
= Complete the restoration and replacement process - AFF A250
:icons: font
:imagesdir: ../media/

[.lead]
You must verify the HA state of the chassis, run diagnostics, and return the failed part to NetApp, as described in the RMA instructions shipped with the kit.

== Step 1: Verify and set the HA state of the chassis

You must verify the HA state of the chassis, and, if necessary, update the state to match your system configuration.

. In Maintenance mode, from either controller module, display the HA state of the local controller module and chassis: `ha-config show`
+
The HA state should be the same for all components.

. If the displayed system state for the chassis does not match your system configuration:
 .. Set the HA state for the chassis: `ha-config modify chassis _HA-state_`
+
The value for HA-state can be one of the following:

  *** `ha`
  *** `mcc`
  *** `mccip`
  *** `non-ha`

 .. Confirm that the setting has changed: `ha-config show`
. If you have not already done so, recable the rest of your system.
. Reinstall the bezel on the front of the system.


== Step 2: Run diagnostics

After you have replaced a component in your system, you should run diagnostic tests on that component.

Your system must be at the LOADER prompt to start diagnostics.

All commands in the diagnostic procedures are issued from the controller where the component is being replaced.

. If the controller to be serviced is not at the LOADER prompt, reboot the controller: `system node halt -node node_name`
+
After you issue the command, you should wait until the system stops at the LOADER prompt.

. At the LOADER prompt, access the special drivers specifically designed for system-level diagnostics to function properly: `boot_diags`
. Select *Scan System* from the displayed menu to enable running the diagnostics tests.
. Select *Test System* from the displayed menu.
. Proceed based on the result of the preceding step:
 ** If the test failed, correct the failure, and then rerun the test.
 ** If the test reported no failures, select Reboot from the menu to reboot the system.

== Step 3: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
