---
permalink: a250/controller-replace-shutdown.html
sidebar: sidebar
keywords: aff a250, shut down the impaired node
summary: To shut down the impaired controller module, you must determine the status of the node and, if necessary, take over the node so that the healthy node continues to serve data from the impaired node storage.
---
= Shut down the impaired controller module - AFF A250
:icons: font
:imagesdir: ../media/

[.lead]
* If you are using NetApp Storage Encryption, you must have reset the MSID using the instructions in the "`Returning SEDs to unprotected mode`" section of the _ONTAP 9 NetApp Encryption Power Guide_.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html[ONTAP 9 NetApp Encryption Power Guide]

* If you have a SAN system, you must have checked event messages (event log show) for impaired node SCSI blade.
+
Each SCSI-blade process should be in quorum with the other nodes in the cluster. Any issues must be resolved before you proceed with the replacement.

* If you have a MetroCluster configuration, you must have confirmed that the MetroCluster Configuration State is configured and that the nodes are in an enabled and normal state (metrocluster node show).

== Option 1: Most systems

include::../_include/shutdown_most_frus.adoc[]

== Option 2: Systems in a MetroCluster configuration

include::../_include/shutdown_any_mcc_supported.adoc[]
