---
permalink: fas8200/controller-replace-recable-reassign-disks.html
sidebar: sidebar
keywords: fas8200, how to recable the system, how to reassign disks
summary: "You must recable the storage and confirm disk reassignment."
---
= Recable the system and reassign disks - FAS8200
:icons: font
:imagesdir: ../media/

[.lead]
Continue the replacement procedure by recabling the storage and confirming disk reassignment.

== Step 1: Recable the system

[.lead]
include::../_include/recable_system_after_controller_rep.adoc[]

== Step 2: Reassign disks

[.lead]
If the storage system is in an HA pair, the system ID of the new controller module is automatically assigned to the disks when the giveback occurs at the end of the procedure. You must use the correct procedure for your configuration.

=== Option 1: Verify the system ID change on an HA system

[.lead]
You must confirm the system ID change when you boot the replacement node and then verify that the change was implemented.

This procedure applies only to systems running ONTAP in an HA pair.

. If the replacement node is in Maintenance mode (showing the `*>` prompt, exit Maintenance mode and go to the LOADER prompt: `halt`
. From the LOADER prompt on the replacement node, boot the node, entering `y` if you are prompted to override the system ID due to a system ID mismatch:``boot_ontap``
. Wait until the Waiting for giveback... message is displayed on the replacement node console and then, from the healthy node, verify that the new partner system ID has been automatically assigned: storage failover show
+
In the command output, you should see a message that the system ID has changed on the impaired node, showing the correct old and new IDs. In the following example, node2 has undergone replacement and has a new system ID of 151759706.
+
----
node1> storage failover show
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----

. From the healthy node, verify that any coredumps are saved:
 .. Change to the advanced privilege level: `set -privilege advanced`
+
You can respond `Y` when prompted to continue into advanced mode. The advanced mode prompt appears (*>).

 .. Save any coredumps: `system node run -node local-node-name partner savecore`
 .. Wait for savecore command to complete before issuing the giveback.
+
You can enter the following command to monitor the progress of the savecore command: `system node run -node local-node-name partner savecore -s`

 .. Return to the admin privilege level: `set -privilege admin`
. Give back the node:
 .. From the healthy node, give back the replaced node's storage: `storage failover giveback -ofnode replacement_node_name`
+
The replacement node takes back its storage and completes booting.
+
If you are prompted to override the system ID due to a system ID mismatch, you should enter `y`.
+
NOTE: If the giveback is vetoed, you can consider overriding the vetoes.
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[Find the High-Availability Configuration Guide for your version of ONTAP 9]

 .. After the giveback has been completed, confirm that the HA pair is healthy and that takeover is possible: storage failover show
+
The output from the `storage failover show` command. should not include the System ID changed on partner message.
. Verify that the disks were assigned correctly: storage disk show -ownership
+
The disks belonging to the replacement node should show the new system ID. In the following example, the disks owned by node1 now show the new system ID, 1873775277:
+
----
node1> storage disk show -ownership

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----

=== Option 2: Manually reassign the system ID on systems in a two-node MetroCluster configuration

[.lead]
include::../_include/2n_mcc_reassign_sysid.adoc[]
