---
permalink: fas9500/fan_swap_out.html
sidebar: sidebar
keywords:
summary: 'To swap out a fan module without interrupting service, you must perform a specific sequence of tasks.'
---
= Swap out a fan - FAS9500
:icons: font
:imagesdir: ../media/

[.lead]
To swap out a fan module without interrupting service, you must perform a specific sequence of tasks.

IMPORTANT: You must replace the fan module within two minutes of removing it from the chassis. System airflow is disrupted and the controller module or modules shut down after two minutes to avoid overheating.

.Steps

. If you are not already grounded, properly ground yourself.
. Remove the bezel (if necessary) with two hands, by grasping the openings on each side of the bezel, and then pulling it toward you until the bezel releases from the ball studs on the chassis frame.
. Identify the fan module that you must replace by checking the console error messages and looking at the Attention LED on each fan module.
. Press the terra cotta button on the fan module and pull the fan module straight out of the chassis, making sure that you support it with your free hand.
+
IMPORTANT: The fan modules are short. Always support the bottom of the fan module with your free hand so that it does not suddenly drop free from the chassis and injure you.

+

++++
<div class="aspect-ratio"><iframe frameborder="1" height="400" scrolling="auto" src="https://netapp.hosted.panopto.com/Panopto/Pages/embed.aspx?id=86b0ed39-1083-4b3a-9e9c-ae78004c2ffc" width="711"> </iframe></div>
++++

ifdef::backend-pdf[]
https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=86b0ed39-1083-4b3a-9e9c-ae78004c2ffc[Animation - Remove/install fan^]
endif::[]

+

image::../media/drw_9500_remove_install_fan.svg[width=340]
+
[cols="20%,80%"]
|===
a|
image::../media/legend_icon_01.svg[width=20]
 a|
Terra cotta release button
a|
image::../media/legend_icon_02.svg[width=20]
 a|
Slide fan in/out of chassis
|===

. Set the fan module aside.
. Align the edges of the replacement fan module with the opening in the chassis, and then slide it into the chassis until it snaps into place.
+
When inserted into a live system, the amber Attention LED flashes four times when the fan module is successfully inserted into the chassis.

. Align the bezel with the ball studs, and then gently push the bezel onto the ball studs.

include::../_include/complete_rma_step.adoc[]
