---
permalink: fas9500/nvram_module_or_nvram_dimm_replacement.html
sidebar: sidebar
keywords:
summary: 'The NVRAM module consists of the NVRAM11 and DIMMs and up to two NVMe SSD Flash Cache modules (FlashCache or caching modules) per NVRAM module.'
---
= Replace the NVRAM module and/or NVRAM DIMMs - FAS9500
:icons: font
:imagesdir: ../media/

[.lead]
The NVRAM module consists of the NVRAM11 and DIMMs. You can replace a failed NVRAM module or the DIMMs inside the NVRAM module. To replace a failed NVRAM module, you must remove it from the chassis, move the DIMMs to the replacement module, and install the replacement NVRAM module into the chassis.

To replace and NVRAM DIMM, you must remove the NVRAM module from the chassis, replace the failed DIMM in the module, and then reinstall the NVRAM module.

.About this task
Because the system ID is derived from the NVRAM module, if replacing the module, disks belonging to the system are reassigned to a new system ID.

.Before you begin
* All disk shelves must be working properly.
* If your system is in an HA pair, the partner node must be able to take over the node associated with the NVRAM module that is being replaced.
* This procedure uses the following terminology:
** The impaired node is the node on which you are performing maintenance.
** The healthy node is the HA partner of the impaired node.
* This procedure includes steps for automatically or manually reassigning disks to the controller module associated with the new NVRAM module. You must reassign the disks when directed to in the procedure. Completing the disk reassignment before giveback can cause issues.
* You must replace the failed component with a replacement FRU component you received from your provider.
* You cannot change any disks or disk shelves as part of this procedure.

== Step 1: Shut down the impaired node

include::../_include/shutdown_most_frus_no_PCM_remove.adoc[]

== Step 2: Replace the NVRAM module

To replace the NVRAM module, locate it in slot 6 in the chassis and follow the specific sequence of steps.

. If you are not already grounded, properly ground yourself.

. Remove the target NVRAM module from the chassis:
.. Depress the lettered and numbered cam button.
+
The cam button moves away from the chassis.

.. Rotate the cam latch down until it is in a horizontal position.
+
The NVRAM module disengages from the chassis and moves out a few inches.

.. Remove the NVRAM module from the chassis by pulling on the pull tabs on the sides of the module face.
+
video::228cbd14-4cb2-49b5-88f1-ae78004b9d84[panopto, title="Animation - Replace the NVRAM module"]
+
image::../media/drw_9500_move-remove_NVRAM_module.svg[width=340]
+

[cols="20%,90%"]
|===
a|
image::../media/legend_icon_01.svg[width=20]
 a|
Lettered and numbered I/O cam latch
a|
image::../media/legend_icon_02.svg[width=20]
a|
I/O latch completely unlocked

|===

. Set the NVRAM module on a stable surface and remove the cover from the NVRAM module by pushing down on the blue locking button on the cover, and then, while holding down the blue button, slide the lid off the NVRAM module.

+

image::../media/drw_9500_remove_NVRAM_module_contents.svg[width=340]
+

[cols="20%,80%"]
|===
a|
image::../media/legend_icon_01.svg[width=20]
 a|
Cover locking button
a|
image::../media/legend_icon_02.svg[width=20]
a|
DIMM and DIMM ejector tabs
|===

. Remove the DIMMs, one at a time, from the old NVRAM module and install them in the replacement NVRAM module.
. Close the cover on the module.
. Install the replacement NVRAM module into the chassis:
 .. Align the module with the edges of the chassis opening in slot 6.
 .. Gently slide the module into the slot until the lettered and numbered I/O cam latch begins to engage with the I/O cam pin, and then push the I/O cam latch all the way up to lock the module in place.

== Step 3: Replace a NVRAM DIMM

To replace NVRAM DIMMs in the NVRAM module, you must remove the NVRAM module, open the module, and then replace the target DIMM.

. If you are not already grounded, properly ground yourself.
. Remove the target NVRAM module from the chassis:
.. Depress the lettered and numbered cam button.
+
The cam button moves away from the chassis.
.. Rotate the cam latch down until it is in a horizontal position.
+
The NVRAM module disengages from the chassis and moves out a few inches.
.. Remove the NVRAM module from the chassis by pulling on the pull tabs on the sides of the module face.
+
video::228cbd14-4cb2-49b5-88f1-ae78004b9d84[panopto, title="Animation - Replace the NVRAM module"]
+
image::../media/drw_9500_move-remove_NVRAM_module.svg[width=340]
+

[cols="20%,80%"]
|===
a|
image::../media/legend_icon_01.svg[width=20]
a|
Lettered and numbered I/O cam latch
a|
image::../media/legend_icon_02.svg[width=20]
a|
I/O latch completely unlocked

|===

. Set the NVRAM module on a stable surface and remove the cover from the NVRAM module by pushing down on the blue locking button on the cover, and then, while holding down the blue button, slide the lid off the NVRAM module.
+
image::../media/drw_9500_remove_NVRAM_module_contents.svg[width=340]
+
[cols="20%,80%"]
|===
a|
image::../media/legend_icon_01.svg[width=20]
a|
Cover locking button
a|
image::../media/legend_icon_02.svg[width=20]
a|
DIMM and DIMM ejector tabs
|===

. Locate the DIMM to be replaced inside the NVRAM module, and then remove it by pressing down on the DIMM locking tabs and lifting the DIMM out of the socket.
+
. Install the replacement DIMM by aligning the DIMM with the socket and gently pushing the DIMM into the socket until the locking tabs lock in place.
. Close the cover on the module.
. Install the NVRAM module into the chassis:
 .. Align the module with the edges of the chassis opening in slot 6.
 .. Gently slide the module into the slot until the lettered and numbered I/O cam latch begins to engage with the I/O cam pin, and then push the I/O cam latch all the way up to lock the module in place.

== Step 4: Reboot the controller after FRU replacement

After you replace the FRU, you must reboot the controller module.

. To boot ONTAP from the LOADER prompt, enter `bye`.

== Step 5: Verify and set the HA state of the controller module

You must verify the `HA` state of the controller module and, if necessary, update the state to match your system configuration.

. In Maintenance mode from the replacement controller module, verify that all components display the same `HA` state: `ha-config show`
+

[options="header" cols="1,2"]

|===
| If your system is in...| The HA state for all components should be...
a|
An HA pair
a|
ha
a|
A MetroCluster FC configuration with four or more nodes
a|
mcc

a|
A MetroCluster IP configuration
a|
mccip
|===

. If the displayed system state of the controller module does not match your system configuration, set the `HA` state for the controller module: `ha-config modify controller _ha-state_`
. If the displayed system state of the chassis does not match your system configuration, set the `HA` state for the chassis: `ha-config modify chassis _ha-state_`

== Step 6: Reassigning disks

You must confirm the system ID change when you boot the replacement node and then verify that the change was implemented.

This procedure applies only to systems running ONTAP in an HA pair.

.Steps
. If the replacement node is in Maintenance mode (showing the `*>` prompt), exit Maintenance mode and go to the LOADER prompt: `halt`
. From the LOADER prompt on the replacement node, boot the node, entering `y` if you are prompted to override the system ID due to a system ID mismatch.
. Wait until the `Waiting for giveback...` message is displayed on the replacement node console and then, from the healthy node, verify that the new partner system ID has been automatically assigned: `storage failover show`
+
In the command output, you should see a message that the system ID has changed on the impaired node, showing the correct old and new IDs. In the following example, node2 has undergone replacement and has a new system ID of 151759706.
+
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----

. From the healthy node, verify that any coredumps are saved:
 .. Change to the advanced privilege level: `set -privilege advanced`
+
You can respond `Y` when prompted to continue into advanced mode. The advanced mode prompt appears (*>).

 .. Save any coredumps: `system node run -node local-node-name partner savecore`
 .. Wait for the `savecore` command to complete before issuing the giveback.
+
You can enter the following command to monitor the progress of the `savecore` command: `system node run -node local-node-name partner savecore -s`

 .. Return to the admin privilege level: `set -privilege admin`
. Give back the node:
 .. From the healthy node, give back the replaced node's storage: `storage failover giveback -ofnode replacement_node_name`
+
The replacement node takes back its storage and completes booting.
+
If you are prompted to override the system ID due to a system ID mismatch, you should enter `y`.
+
NOTE: If the giveback is vetoed, you can consider overriding the vetoes.
+
For more information, see the https://docs.netapp.com/us-en/ontap/high-availability/ha_manual_giveback.html#if-giveback-is-interrupted[Manual giveback commands^] topic to override the veto.

 .. After the giveback has been completed, confirm that the HA pair is healthy and that takeover is possible: `storage failover show`
+
The output from the storage failover show command should not include the System ID changed on partner message.
. Verify that the disks were assigned correctly: `storage disk show -ownership`
+
The disks belonging to the replacement node should show the new system ID. In the following example, the disks owned by node1 now show the new system ID, 1873775277:
+
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----

. If the system is in a MetroCluster configuration, monitor the status of the node: `metrocluster node show`
+
The MetroCluster configuration takes a few minutes after the replacement to return to a normal state, at which time each node will show a configured state, with DR Mirroring enabled and a mode of normal. The `metrocluster node show -fields node-systemid` command output displays the old system ID until the MetroCluster configuration returns to a normal state.

. If the node is in a MetroCluster configuration, depending on the MetroCluster state, verify that the DR home ID field shows the original owner of the disk if the original owner is a node on the disaster site.
+
This is required if both of the following are true:

** The MetroCluster configuration is in a switchover state.
** The replacement node is the current owner of the disks on the disaster site.
+
See https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#disk-ownership-changes-during-ha-takeover-and-metrocluster-switchover-in-a-four-node-metrocluster-configuration[Disk ownership changes during HA takeover and MetroCluster switchover in a four-node MetroCluster configuration^] for more information.

. If your system is in a MetroCluster configuration, verify that each node is configured: `metrocluster node show - fields configuration-state`
+
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----

. Verify that the expected volumes are present for each node: `vol show -node node-name`
. If you disabled automatic takeover on reboot, enable it from the healthy node: `storage failover modify -node replacement-node-name -onreboot true`

== Step 7: Restore Storage and Volume Encryption functionality

include::../_include/restore_storage_encryption.adoc[]

== Step 8: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
