---
sidebar: upgrade-arl-auto_sidebar
permalink: upgrade-arl-auto/config_fc_ports_node3.html
keywords: configure, fc, port, uta, uta2, upgrade, adapter, V-series, FlexArray Virtualization
summary: Set port configurations on the node before you bring it into service because the ports are not preconfigured.
---

= Configure FC ports on node3
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If node3 has FC ports, either onboard or on an FC adapter, you must set port configurations on the node before you bring it into service because the ports are not preconfigured. If the ports are not configured, you might experience a disruption in service.

.Before you begin

You must have the values of the FC port settings from node1 that you saved in the section link:prepare_nodes_for_upgrade.html[Prepare the nodes for upgrade].

.About this task

You can skip this section if your system does not have FC configurations. If your system has onboard UTA/UTA2 ports or a UTA/UTA2 card, you configure them in link:check_config_uta_uta2_ports_node3.html[Check and configure UTA/UTA2 ports on node3]

*Important*: If your system has storage disks, enter the commands in this section at the cluster prompt. If you have a 'V-Series system' or have FlexArray Virtualization Software and are connected to storage arrays, enter commands in this section in Maintenance mode.

include::../_include/ru_config_fc_ports_node3.adoc[]

. [[step8]]Take one of the following actions:
+
|===
|If the system that you are upgrading... |Then…

|Has storage disks
a|* If node3 has a UTA/UTA2 card or UTA/UTA2 onboard ports, go to the section link:check_config_uta_uta2_ports_node3.html[Check and configure UTA/UTA2 ports on node3].
* If node3 does not have a UTA/UTA2 card or UTA/UTA2 onboard ports, skip the section link:check_config_uta_uta2_ports_node3.html[Check and configure UTA/UTA2 ports on node3]. and go to the section link:map_ports_node1_node3.html[Map ports from node1 to node3].
|Is a V-Series system or has FlexArray Virtualization Software and is connected to storage arrays
a|* If node3 has a UTA/UTA2 card or UTA/UTA2 onboard ports, go to the section link:check_config_uta_uta2_ports_node3.html[Check and configure UTA/UTA2 ports on node3].
* If node3 does not have a UTA/UTA2 card or UTA/UTA2 onboard ports, skip the section link:check_config_uta_uta2_ports_node3.html[Check and configure UTA/UTA2 ports on node3] and return to link:install_boot_node3.html[Install and boot node3] and resume the section at link:install_boot_node3.html#step23[Step 23].
|===
// bottom half of p. 31, page 32, and top of 33 in PDF
