---
sidebar: upgrade-arl-auto_sidebar
permalink: upgrade-arl-auto/guidelines_for_upgrading_controllers_with_arl.html
keywords: upgrade, controllers, guidelines, ARL, aggregate relocation, supported upgrades, two-node, cluster, troubleshoot
summary: Upgrading a pair of controllers running ONTAP 9.5 to ONTAP 9.7 depends on the platform and the configuration of both the original and replacement controllers.
---

= Guidelines for upgrading controllers with ARL
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To understand whether you can use aggregate relocation (ARL) to upgrade a pair of controllers running ONTAP 9.5 to ONTAP 9.7 depends on the platform and the configuration of both the original and replacement controllers.

== Supported upgrades for ARL

When you upgrade a pair of nodes using this ARL procedure for ONTAP 9.5 to ONTAP 9.7, you must verify that ARL can be performed on the original and replacement controllers.

You should check the size of all defined aggregates and number of disks supported by the original system. You must then compare the aggregate sizes and number of disks supported to the aggregate size and number of disks supported by the new system. This information is available in the _Hardware Universe_ at hwu.netapp.com. The aggregate size and the number of disks supported by the new system must be equal to or greater than the aggregate size and number of disks supported by the original system.

You should validate in the cluster mixing rules whether new nodes can become part of the cluster with the existing nodes, when the original controller is replaced. For more information about cluster mixing rules, see the link:https://hwu.netapp.com[Hardware Universe].

NOTE: Before performing an AFF system upgrade, you must upgrade ONTAP to release versions 9.5P1 or later. These release levels are required for a successful upgrade.

NOTE: If you are upgrading a system that supports internal drives (for example, an FAS2700 or AFF A250) but does NOT have internal drives, use the procedure in _Using Aggregate Relocation to Upgrade Controller Hardware Running ONTAP 9.0 to 9.4._

Controller upgrade using ARL is supported on systems configured with SnapLock Enterprise andSnapLock Compliance volumes.

== Two-node switchless clusters

If you are upgrading nodes in a two-node switchless cluster, you can leave the nodes in the switchless cluster while performing the upgrade. You do not need to convert them to a switched cluster.

== Upgrades not supported for ARL

You cannot perform the following upgrades:

* To replacement controllers that do not support the disk shelves connected to the original controllers
+
See the link:https://hwu.netapp.com[Hardware Universe] for disk-support information.

* To entry level controllers with internal drives, for example: an FAS 2500.
+
If you want to upgrade entry level controllers with internal drives, see the procedure _Upgrading a pair of nodes running clustered Data ONTAP by moving volumes_ in _Controller Hardware Upgrade Express Guide_.

== Troubleshooting

If any problems occur while upgrading the controllers, you can refer to the link:troubleshoot.html[Troubleshoot] section at the end of the procedure for more information and possible solutions.

If you do not find a solution to the problem you encountered, you should contact technical support.
// p.9 of PDF
