---
sidebar: upgrade-arl-auto_sidebar
permalink: upgrade-arl-auto/install_and_boot_node4.html
keywords: install, boot, node4, install ONTAP
summary: You must install node4 in the rack, transfer node2's connections to node4, boot node4, and install ONTAP.
---

= Install and boot node4
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

include::../_include/ru_install_and_boot_node4_intro_to_step_5.adoc[]

[start=6]
.  [[Step6]]Configure the netboot connection by choosing one of the following actions.
+
NOTE: You should use the management port and IP as the netboot connection. Do not use a data LIF IP or a data outage might occur while the upgrade is being performed.

+
|===
|If Dynamic Host Configuration Protocol (DHCP) is... |Then...

|Running
|Configure the connection automatically by entering the following command at the boot environment prompt:
`ifconfig e0M -auto`
|Not running
|Manually configure the connection by entering the following command at the boot environment prompt:
`ifconfig e0M -addr=filer_addr -mask=netmask -gw=gateway dns=dns_addr domain=dns_domain`
`filer_addr` is the IP address of the storage system.
`netmask` is the network mask of the storage system.
`gateway` is the gateway for the storage system.
`dns_addr` is the IP address of a name server on your network.
`dns_domain` is the Domain Name Service (DNS) domain name. If you use this optional parameter, you do not need a fully qualified domain name in the netboot server URL; you need only the server's host name.

*Note:* Other parameters might be necessary for your interface. Enter help ifconfig at the firmware prompt for details.
|===

include::../_include/ru_install_and_boot_node4_step_7_to_28.adoc[]
+
[start=Step29]
. [[Step29]]For MetroCluster configuration, V-Series systems and systems with FlexArray Virtualization software connected to storage arrays, go to link:setting_the_fc_or_uta_uta2_configuration_on_node4.html#Step15[Step 15].
