---
sidebar: upgrade-arl-auto_sidebar
permalink: upgrade-arl-auto/set_fc_or_uta_uta2_config_node4.html
keywords: aggregate relocation, YYYYY
summary: ZZZZZZ
---

= Set the FC or UTA/UTA2 configuration on node4
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

If node4 has onboard FC ports, onboard unified target adapter (UTA/UTA2) ports, or a UTA/UTA2 card, you must configure the settings before completing the rest of the procedure.

.About this task

You might need to complete the link:config_fc_ports_node4,html[Configure FC ports on node4] section, the link:check_config_uta_uta2_ports_node4[Check and configure UTA/UTA2 ports on node4 section], or both sections.

NOTE: If node4 does not have onboard FC ports, onboard UTA/UTA2 ports, or a UTA/UTA2 card, and you are upgrading a system with storage disks, you can skip to the link:map_ports_node2_node4.html[Mapp ports from node2 to node4] section.
However, if you have a V-Series system or have FlexArray Virtualization Software and are connected to storage arrays, and node4 does not have onboard FC ports, onboard UTA/ UTA2 ports, or a UTA/UTA2 card, you must return to the link:install_and_boot_node4.html[Install and boot node4] section and resume at Step 22. Make sure that node4 has sufficient rack space. If node4 is in a separate chassis from node2, you can put node4 in the same location as node3. If node2 and node4 are in the same chassis, then node4 is already in its appropriate rack location.

.Choices

* link:config_fc_ports_node4,html[Configure FC ports on node4]
* link:check_config_uta_uta2_ports_node4[Check and configure UTA/UTA2 ports on node4 section]

include::../_include/ru_config_fc_ports_node4.adoc[]

. Take one of the following actions:
+
|===
|If the system that you are upgrading...
|Then...

|Has storage disks
a|* Skip this section and go to link:map_ports_node2_node4.adoc.html[Map ports from node2 to node4] if node4 does not have a UTA/UTA2 card or UTA/UTA2 onboard ports.

|Is a V-Series system or has FlexArray Virtualization Software and is connected to storage arrays
a|* Go to Checking and configuring UTA/UTA2 ports on node4 if node4 has a UTA/UTA2 card or UTA/UTA2 onboard ports.
* Skip the section Checking and configuring UTA/UTA2 ports on node4 if node4 does not have a UTA/UTA2 card or UTA/UTA2 onboard ports, return to the section link:install_and_boot_node4.html[Install and boot node4], and resume the section at Step 23.
|===

include::../_include/ru_check_config_uta_uta2_ports_node4_intro_to_step_11.adoc[]

. Take one of the following actions:
+
|===
|If the system... |Then...

|Has storage disks |Go to the section link:map_ports_node2_node4.html[Mapp ports from node2 to node4].
|Is a V-Series system or has FlexArray Virtualization Software and is connected to storage arrays
|Return to the section link:install_and_boot_node4.html[Install and boot node4] and resume the section at step 23.
|===

. Exit Maintenance mode:
+
`halt`

. Boot node into boot menu:
+
`boot_ontap menu`
+
If you are upgrading to an A800, go to <<Step23,Step 23>>.

. On node4, go to the boot menu, and using 22/7, select the hidden option 'boot_after_controller_replacement'. At the prompt, enter node2 to reassign the disks of node2 to node4, as per the following example.
+
----
LOADER-A> boot_ontap menu ...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
.
Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? 22/7
.
.
(boot_after_controller_replacement) Boot after controller upgrade
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.

Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? boot_after_controller_replacement
.
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes
.
.
Controller Replacement: Provide name of the node you would like to replace: <name of the node being replaced>
.
.
Changing sysid of node <node being replaced> disks.
Fetched sanown old_owner_sysid = 536953334 and calculated old sys id = 536953334
Partner sysid = 4294967295, owner sysid = 536953334
.
.
.
Terminated
<node reboots>
.
.
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
.
.
System rebooting...
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
Login: ...
----

. If the system goes into a reboot loop with the message `no disks found`, this is because it has reset the ports back to the target mode and therefore is unable to see any disks. Continue with <<Step17,Step 17>> through <<Step22,Step 22>> to resolve this.

include::../_include/ru_check_config_uta_uta2_ports_node4_step_17_to_23.adoc[]
