---
sidebar: upgrade-arl-auto_sidebar
permalink: upgrade-arl-auto/set_fc_or_uta_uta2_config_on_node3.html
keywords: FC, UTA, UTA2, configure, node3, CNA adapters, onboard ports, FlexArray Virtualization
summary: Cconfigure port and card settings before completing the rest of the procedure.
---

= Set the FC or UTA/UTA2 configuration on node3
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If node3 has onboard FC ports, onboard unified target adapter (UTA/UTA2) ports, or a UTA/UTA2 card, you must configure the settings before completing the rest of the procedure.

.About this task

You might need to complete the section link:config_fc_ports_node3.html[Configure FC ports on node3], the section link:check_configure_uta_uta2_ports_node3.html[Check and configure UTA/UTA2 ports on node3], or both sections.

[NOTE]
NetApp marketing materials might use the term UTA2 to refer to CNA adapters and ports. However, the CLI uses the term CNA.

* If node3 does not have onboard FC ports, onboard UTA/UTA2 ports, or a UTA/UTA2 card, and you are upgrading a system with storage disks, you can skip to the link:map_ports_node1_node3.html[Map ports from node1 to node3] section.
* However, if you have a V-Series system or a system with FlexArray Virtualization software with storage arrays, and node3 does not have onboard FC ports, onboard UTA/UTA ports, or a UTA/UTA2 card, return to the section link:install_boot_node3.html[Install and boot node3] and resume the section at link:install_boot_node3.html#step23[Step 23].

.Choices

* link:config_fc_ports_node3.html[Configure FC ports on node3]
* link:check_configure_uta_uta2_ports_node3.html[Check and configure UTA/UTA2 ports on node3]
// top section of page 31 in PDF
