Before shutting down the impaired node, you need to check whether the system has either NetApp Volume Encryption (NVE) or NetApp Storage Encryption (NSE) enabled. If so, you need to verify the configuration.

.Steps
. Connect the console cable to the impaired node.
. Check whether NVE is configured for any volumes in the cluster: `volume show -is-encrypted true`
+
If any volumes are listed in the output, NVE is configured and you need to verify the NVE configuration. If no volumes are listed, check whether NSE is configured.

. Check whether NSE is configured: `storage encryption disk show`
 ** If the command output list the drive details with Mode & Key ID information, NSE is configured and you need to verify the NSE configuration.
 ** If NVE and NSE are not configured, it's safe to shut down the impaired node.

=== Verifying NVE configuration
.Steps
. Display the key IDs of the authentication keys that are stored on the key management servers: `security key-manager query`
 ** If the `Restored` column displays `yes` and all key managers display `available`, it's safe to shut down the impaired node.
 ** If the `Restored` column displays anything other than `yes`, or if any key manager displays `unavailable`, you need to complete some additional steps.
 ** If you see the message This command is not supported when onboard key management is enabled, you need to complete some other additional steps.
. If the `Restored` column displayed anything other than `yes`, or if any key manager displayed `unavailable`:
 .. Retrieve and restore all authentication keys and associated key IDs: `security key-manager restore -address *`
+
If the command fails, contact NetApp Support.
+
http://mysupport.netapp.com/[mysupport.netapp.com]

 .. Verify that the `Restored` column displays `yes` for all authentication keys and that all key managers display `available`: `security key-manager query`
 .. Shut down the impaired node.
. If you saw the message This command is not supported when onboard key management is enabled, display the keys stored in the onboard key manager: `security key-manager key show -detail`
 .. If the `Restored` column displays `yes` manually backup the onboard key management information:
  * Go to advanced privilege mode and enter `y` when prompted to continue: `set -priv advanced`
  * Enter the command to display the OKM backup information: `security key-manager backup show`
  * Copy the contents of the backup information to a separate file or your log file. You'll need it in disaster scenarios where you might need to manually recover OKM.
  * Return to admin mode: `set -priv admin`
  * Shut down the impaired node.
 .. If the `Restored` column displays anything other than `yes`:
  * Run the key-manager setup wizard: `security key-manager setup -node target/impaired node name`
+
NOTE: Enter the customer's onboard key management passphrase at the prompt. If the passphrase cannot be provided, contact http://mysupport.netapp.com/[mysupport.netapp.com]

  * Verify that the `Restored` column displays `yes` for all authentication key: `security key-manager key show -detail`
  * Go to advanced privilege mode and enter `y` when prompted to continue: `set -priv advanced`
  * Enter the command to display the OKM backup information:``security key-manager backup show``
  * Copy the contents of the backup information to a separate file or your log file. You'll need it in disaster scenarios where you might need to manually recover OKM.
  * Return to admin mode: `set -priv admin`
  * You can safely shutdown the node.

=== Verifying NSE configuration
.Steps
. Display the key IDs of the authentication keys that are stored on the key management servers: `security key-manager query`
 ** If the `Restored` column displays `yes` and all key managers display `available`, it's safe to shut down the impaired node.
 ** If the `Restored` column displays anything other than `yes`, or if any key manager displays `unavailable`, you need to complete some additional steps.
 ** If you see the message This command is not supported when onboard key management is enabled, you need to complete some other additional steps
. If the `Restored` column displayed anything other than `yes`, or if any key manager displayed `unavailable`:
 .. Retrieve and restore all authentication keys and associated key IDs: `security key-manager restore -address *`
+
If the command fails, contact NetApp Support.
+
http://mysupport.netapp.com/[mysupport.netapp.com]

 .. Verify that the `Restored` column displays `yes` for all authentication keys and that all key managers display `available`: `security key-manager query`
 .. Shut down the impaired node.
. If you saw the message This command is not supported when onboard key management is enabled, display the keys stored in the onboard key manager: `security key-manager key show -detail`
 .. If the `Restored` column displays `yes`, manually backup the onboard key management information:
  * Go to advanced privilege mode and enter `y` when prompted to continue: `set -priv advanced`
  * Enter the command to display the OKM backup information: `security key-manager backup show`
  * Copy the contents of the backup information to a separate file or your log file. You'll need it in disaster scenarios where you might need to manually recover OKM.
  * Return to admin mode: `set -priv admin`
  * Shut down the impaired node.
 .. If the `Restored` column displays anything other than `yes`:
  * Run the key-manager setup wizard: `security key-manager setup -node target/impaired node name`
+
NOTE: Enter the customer's OKM passphrase at the prompt. If the passphrase cannot be provided, contact http://mysupport.netapp.com/[mysupport.netapp.com]

  * Verify that the `Restored` column shows `yes` for all authentication keys: `security key-manager key show -detail`
  * Go to advanced privilege mode and enter `y` when prompted to continue: `set -priv advanced`
  * Enter the command to backup the OKM information:``security key-manager backup show``
+
NOTE: Make sure that OKM information is saved in your log file. This info will be needed in disaster scenarios where OKM might need to be manually recovered.

  * Copy the contents of the backup information to a separate file or your log. You'll need it in disaster scenarios where you might need to manually recover OKM.
  * Return to admin mode: `set -priv admin`
  * You can safely shutdown the node.
