This guide describes how to upgrade the controller hardware without disruption by using aggregate relocation.

You can nondisruptively upgrade the controller hardware on a pair of nodes running NetApp ONTAP by migrating non-root aggregates from the original nodes to the new nodes in the same cluster. The data hosted on the nodes that are being upgraded is accessible during the upgrade.

This procedure uses a method called aggregate relocation (ARL), which takes advantage of the HA configuration to enable you to move ownership of non-root aggregates from one node to another if they share storage within the same cluster.

There are two ARL methods for upgrading your controller hardware, by using system commands or by performing a manual upgrade. Before you start, review the list of ARL guides in the tables below to verify that you have selected the correct guide for your controller hardware upgrade.

[cols=2*,options="header",cols="30,70"]
|===
|If you’re running this ONTAP version…
|To upgrade with system commands, use…
|9.8
|link:https://docs.netapp.com/us-en/ontap-systems/upgrade-arl-auto-app/[Using "system controller replace" Commands to Upgrade Controller Hardware Running ONTAP 9.8]
|9.5 to 9.7
|link:https://docs.netapp.com/us-en/ontap-systems/upgrade-arl-auto/[Using "system controller replace" Commands to Upgrade Controller Hardware Running ONTAP 9.5 to ONTAP 9.7]
|===

[cols=2*,options="header",cols="30,70"]
|===
|If you’re running this ONTAP version…
|To manually upgrade, use…
|9.8 or later
<<<<<<< HEAD
|link:https://docs.netapp.com/us-en/ontap-systems/upgrade-arl-manual-app/[Using Aggregate Relocation to Manually Upgrade Controller Hardware Running ONTAP 9.8 or Later]
|9.0 to 9.7
|link:https://docs.netapp.com/us-en/ontap-systems/upgrade-arl-manual/[Using Aggregate Relocation to Manually Upgrade Controller Hardware Running ONTAP 9.7 or Earlier]
=======
|link:https://docs.netapp.com/us-en/ontap-systems/upgrade-arl-manual-app/[Using Aggregate Relocation to Manually Upgrade Controller Hardware Running ONTAP 9.8 and Later]
|9.0 to 9.7
|link:https://docs.netapp.com/us-en/ontap-systems/upgrade-arl-manual/[Using Aggregate Relocation to Manually Upgrade Controller Hardware Running ONTAP 9.7 and Earlier]
>>>>>>> fed26d72e3d1a44b3fe94c50698fbbb68036b8e5
|===
