. [[step17]]Press Ctrl-C during autoboot to stop the node at the `LOADER>` prompt.

. [[step18]]At the loader prompt, enter maintenance mode by using the following command:
+
`boot_ontap maint`

. [[step19]]In maintenance mode, display all the previously set initiator ports that are now in target mode by using the following command:
+
`ucadmin show`
+
Change the ports back to initiator mode by using the following command:
+
`ucadmin modify -m fc -t initiator -f <adapter name>`

. [[step20]]Verify that the ports have been changed to initiator mode by using the following command:
+
`ucadmin show`

. [[step21]]Exit maintenance mode by using the following command:
+
`halt`

. [[step22]]At the loader prompt boot up, by using the following command:
+
`boot_ontap`
+
Now, on booting, the node can detect all the disks that were previously assigned to it and can boot up as expected.

. [[step23]]If you are upgrading from a system with external disks to a system that supports internal and external disks (AFF A800 systems, for example), set the node1 aggregate as the root aggregate to ensure node3 boots from the root aggregate of node1. To set the root aggregate, go to the boot menu and select option `5` to enter maintenance mode.
+
CAUTION: You must perform the following substeps in the exact order shown; failure to do so might cause an outage or even data loss.
+

The following procedure sets node3 to boot from the root aggregate of node1:

.. Enter maintenance mode by using the following command:
+
`boot_ontap maint`

.. Check the RAID, plex, and checksum information for the node1 aggregate by using the following command:
+
`aggr status -r`

.. Check the status of the node1 aggregate by using the following command:
+
`aggr status`

.. If necessary, bring the node1 aggregate online by using the following command:
+
`aggr_online root_aggr_from_<node1>`

.. Prevent the node3 from booting from its original root aggregate by using the following command:
+
`aggr offline <root_aggr_on_node3>`

.. Set the node1 root aggregate as the new root aggregate for node3 by using the following command:
+
`aggr options aggr_from_<node1> root`

.. Verify that the root aggregate of node3 is offline and the root aggregate for the disks brought over from node1 is online and set to root by using the following command:
+
`aggr status`
+
NOTE: Failing to perform the previous substep might cause node3 to boot from the internal root aggregate, or it might cause the system to assume a new cluster configuration exists or prompt you to identify one.
+
The following shows an example of the command output:
+
----
 -----------------------------------------------------------------
 Aggr                 State    Status             Options

 aggr0_nst_fas8080_15 online   raid_dp, aggr      root, nosnap=on
                               fast zeroed
                               64-bit

 aggr0                offline  raid_dp, aggr      diskroot
                               fast zeroed
                               64-bit
 -----------------------------------------------------------------
----

// This reuse file is used in the following adoc files:
// -- upgrade-arl-auto-app/setting_the_fc_oor_uta_uta2_configuration_on_node1.adoc
// -- upgrade-arl-auto/checl_config_uta_uta2_ports_node3.adoc
