---
sidebar: upgrade-arl-manual_sidebar
permalink: upgrade-arl-manual/determine_new_cabling_layout.html
keywords: cable, cabling, layout, disk shelf, fc switches
summary:  Determine the cabling for the new controller modules and any new disk shelves to the existing FC switches.

---

= Determine the new cabling layout
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You must determine the cabling for the new controller modules and any new disk shelves to the existing FC switches.

.About this task

This task must be performed at each MetroCluster site.

.Step

Use the _Fabric-attached MetroCluster Installation and Configuration Guide_  to determine the cabling layout for your switch type, using the port usage for an eight-node MetroCluster configuration.

The FC switch port usage must match the usage described in the guide so that the Reference Configuration Files (RCFs) can be used.
+
link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-fabric/home.html[Fabric-attached MetroCluster Installation and Configuration Guide]
+
NOTE: If your environment cannot be cabled in a way that RCFs can be used, then contact technical support. Do not use this procedure if the cabling cannot use RCFs.
