---
sidebar: upgrade-arl-manual_sidebar
permalink: upgrade-arl-manual/install_boot_node3.html
summary: summary: You need to install node3 in the rack, transfer node1's connections to node3, boot node3, and install ONTAP.
---

= Install and boot node3
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
// COPIED FROM 9.8 GUIDE...CHECK FOR REUSE, THEN REMOVE THIS COMMENT
You need to install node3 in the rack, transfer node1's connections to node3, boot node3, and install ONTAP. You must then reassign any of node1's spare disks, any disks belonging to the root volume, and any non-root aggregates not relocated to node2 earlier, as outlined in the section.

.About this task

The relocation operation is paused at the beginning of this stage. This process is largely automated; the operation pauses to allow you to check its status. You must manually resume the operation. In addition, you must verify that the SAN LIFs have successfully moved to node3.

You need to netboot node3 if it does not have the same version of ONTAP 9 that is installed on node1. After you install node3, boot it from the ONTAP 9 image stored on the web server. You can then download the correct files to the boot media device for subsequent system boots by following
instruction in _Preparing for netboot_ on page 27.

NOTE: *Important*: If you are upgrading a V-Series system connected to storage arrays or a system with
FlexArray Virtualization software that is connected to storage arrays, you need to complete Step
1 on page 36 through Step 5 on page 37, and then leave this section at Step 21 and follow
instructions in the _Configuring Fibre Channel ports on node3_ and _Checking and configuring
CNA ports on node3_ sections as needed, entering commands in Maintenance mode. You must
then return to this section and resume with Step 22 on page 40.
+
If you are upgrading a system with storage disks, you need to complete this entire section and
then go to the _Configuring Fibre Channel ports on node3_ and _Checking and configuring
CNA ports on node3_ sections, entering commands at the cluster prompt.

.Steps

. Make sure that you have rack space for node3.

+
If node1 and node2 were in separate chassis, you can put node3 in the same rack location as node1. However, if node1 was in the same chassis with node2, then you need to put node3 into its own rack space, preferably close to the location of node1.

. Install node3 in the rack, following instructions in the _Installation and Setup Instructions_ for your node model.
+
NOTE: If you are upgrading to a system with both nodes in the same chassis, install node4 in the chassis as well as node3. If you do not, when you boot node3, the node will behave as if it were in a dual-chassis configuration, and when you boot node4, the interconnect between the nodes will not come up.

. Cable node3, moving the connections from node1 to node3.
+
Cable the following connections, using the instructions in the _Installation and Setup Instructions_ or the _FlexArray Virtualization Installation Requirements and Reference_ for the node3 platform, the appropriate disk shelf guide, and the _ONTAP 9 High-Availability
Configuration Guide:
+
* Console (remote management port)
* Cluster ports
* Data ports
* Cluster and node management ports
* Storage
* SAN configurations: iSCSI Ethernet and FC switch ports
+
NOTE: You do not need to move the interconnect card or the cluster interconnect cable connection from node1 to node3 because most platform models have a unique interconnect card model.
+
NOTE: For the MetroCluster configuration, you need to move the FC-VI cable connections from node1 to node3. If the new host does not have an FC-V1 card, you might need to move the FC-VI card.

. Turn on the power to node3, and then interrupt the boot process by pressing Ctrl-C at the console terminal to access the boot environment prompt.
+
If you are upgrading to a system with both nodes in the same chassis, node4 also reboots. However, you can disregard the node4 boot until later.
+
NOTE: When you boot node3, you might see the following warning message:
+
....
WARNING: The battery is unfit to retain data during a power
 outage. This is likely because the battery is
 discharged but could be due to other temporary
 conditions.
 When the battery is ready, the boot process will
 complete and services will be engaged.
 To override this delay, press 'c' followed by 'Enter'
....

. If you see the warning message in Step 4 on page 37, take the following actions:

.. Check for any console messages that might indicate a problem other than a low NVRAM battery, and, if necessary, take any required corrective action.
.. Allow the battery to charge and the boot process to complete.
+
NOTE: *Attention*: Do not override the delay; failure to allow the battery to charge could result in a loss of data.
+
NOTE: Refer to _Preparing for netboot_ on page 27.

. Configure the netboot connection by choosing one of the following actions:
+
NOTE: You should use the management port and IP as the netboot connection. Do not use a data LIF IP or a data outage might occur while the upgrade is being performed.
+
cols[35,65]
|===
|If Dynamic Host Configuration Protocol (DHCP) is... |Then...

|Running
|Configure the connection automatically by entering the following command at the boot environment prompt:

`ifconfig e0M -auto`
|Not running
|Manually configure the connection by entering the following command at the boot environment prompt:

`ifconfig e0M -addr _filer_address_ -mask _netmask_ -gw _gateway_ -dns _dns_address_ domain _dns_domain_`

* _filer_address_ is the IP address of the storage system.
* _netmask_ is the network mask of the storage system.
* _gateway_ is the gateway of the storage system.
* _dns_address_ is the IP address of a name server on your network. This parameter is optional.
* _dns_domain_ is the Domain Name Service (DNS) domain name. This parameter is optional.

*Note:* Other parameters might be necessary for your interface. Enter `help ifconfig` at the firmware prompt for details.
|===

. Perform a netboot on node3:
+
cols[35,65]
|===
|For... |Then enter...

|FAS/AFF8000 series systems
|`netboot http://<web_server_ip>/<path_to_webaccessible_directory>/netboot/kernel`
|All other systems
|`netboot http://<web_server_ip>/<path_to_webaccessible_directory>/<ontap_version>_image.tgz`
|===
+
The path_to_the_web-accessible_directory should lead to where you downloaded the <ontap_version>_image.tgz in Step 1 in the section _Preparing for netboot_ on page 27.
+
NOTE: Do not interrupt the boot.

. From the boot menu, select option *(7) Install new software first*. This menu option downloads and installs the new ONTAP image to the boot device.
+
NOTE:
+
* Disregard the following message:
+
....
This procedure is not supported for Non-Disruptive Upgrade on an HA pair.
....
+
The message applies to nondisruptive upgrades of ONTAP and not upgrades of controllers.

*Always use netboot to update the new node to the desired image. If you use another method to install the image on the new controller, the wrong image might install. This issue applies to all ONTAP releases.

. When you are prompted to continue the procedure, enter y, and when prompted for the package enter the following URL:
+
`http://<web_server_ip>/<path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. Complete the following substeps to reboot the controller module:
.. Enter `n` to skip the backup recovery when you see the following prompt:
+
....
Do you want to restore the backup configuration now? {y|n}
....

.. Reboot by entering `y` when you see the following prompt:
+
....
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
....
+
The controller module reboots but stops at the boot menu because the boot device was reformatted, and the configuration data needs to be restored.

. Select *maintenance mode 5* from the boot menu and enter `y` when you are prompted to continue with the boot.

. Verify that the controller and chassis are configured as HA by using the following command:
+
`ha-config show`
+
The following example shows the output of the ha-config show command:
+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+
NOTE: Systems record in a PROM whether they are in an HA pair or stand-alone configuration. The state must be the same on all components within the stand-alone system or HA pair.

. If the controller and chassis are not configured as HA, use the following commands to correct the configuration:
+
`ha-config modify controller ha`
+
`ha-config modify chassis ha`
+
If you have a Fabric MetroCluster configuration, use the following commands to modify the controller and chassis:
+
`ha-config modify controller mcc`
+
`ha-config modify chassis mcc`

. Exit maintenance mode by using the following command:
+
`halt`
+
Interrupt the autoboot by pressing Ctrl-C at the boot environment prompt.

. On node2, check the system date, time, and time zone by using the following command:
+
`date`

. On node3, check the date by using the following command at the boot environment prompt:
+
`show date`

. If necessary, set the date on node3 by using the following command:
+
`set date mm/dd/yyyy`

. On node3, check the time by entering the following command at the boot environment prompt:
+
`show time`

. If necessary, set the time on node3 by using the following command:
+
`set time hh:mm:ss`

. If necessary, set the partner system ID on node3 by using the following command:
+
`setenv partner-sysid node2_sysid`
+
Save the settings:
+
`saveenv`

. On the new nnode, in boot loader, the partner-sysid parameter needs to be set. For node3, partner-sysid needs to be that of node2. Verify the partner- sysid for node3 using the following command:
+
`printenv partner-sysid`

. Add the FC initiator ports of the new node to the switch zones.
+
If your system has a tape SAN, then you need zoning for the initiators. If required, modify the onboard ports to initiator by referring to Configuring FC ports on node3. See your storage array and zoning documentation for further instructions on zoning.

. Add the FC initiator ports to the storage array as new hosts, mapping the array LUNs to the new hosts.
+
See your storage array and zoning documentation for instructions.

. Modify the World Wide Port Name (WWPN) values in the host or volume groups associated with array LUNs on the storage array.
+
Installing a new controller module changes the WWPN values associated with each onboard FC port.

. If your configuration uses switch-based zoning, adjust the zoning to reflect the new WWPN values.

. If NetApp Storage Encryption (NSE) is in use on this configuration, the `setenv bootarg.storageencryption.support` command must be set to *true*, and the
`kmip.init.maxwait` variable needs to be set to *off* to avoid a boot loop after the node1 configuration is loaded:
+
`setenv bootarg.storageencryption.support true`
+
`setenv kmip.init.maxwait off`

. Boot the node into the boot menu by using the following command:
+
`boot ontap menu`

. For MetroCluster configurations, V-Series systems, and systems with FlexArray Virtualization software connected to storage arrays, you must set and configure the FC or UTA/UTA2 ports on node3 to detect the disks attached to the node. To complete this task, go to _Setting the FC or UTA/UTA2 configuration on node3_ and _Configuring FC ports on node3_.
