---
sidebar: upgrade-arl-manual_sidebar
permalink: upgrade-arl-manual/set_fc_uta_uta2_config_node3.html
summary: Settings must be configured befoe completing the upgrade.
---

= Set the FC or UTA/UTA2 configuration on node3
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
// COPIED FROM 9.8 GUIDE...CHECK FOR REUSE, THEN REMOVE THIS COMMENT
If node3 has onboard FC ports, onboard unified target adapter (UTA/UTA2) ports, or a UTA/UTA2 card, you must configure the settings before completing the rest of the procedure.

.About this task

You might need to complete the section "Configuring FC ports on node3", the section "Checking and configuring UTA/UTA2 ports on node3", or both sections.

NOTE: NetApp marketing materials might use the term UTA2 to refer to CNA adapters and ports. However, the CLI uses the term CNA.

* If node3 does not have onboard FC ports, onboard UTA/UTA2 ports, or a UTA/UTA2 card, and you are upgrading a system with storage disks, you can skip to the section _Mapping ports from node1 to node3_.

* However, if you have a V-Series system or a system with FlexArray Virtualization software with storage arrays, and node3 does not have onboard FC ports, onboard UTA/UTA ports, or a UTA/UTA2 card, return to the section _Installing and booting node3_ and resume the section at Step 22 on page 40.
