---
sidebar: upgrade-arl-manual_sidebar
permalink: upgrade-arl-manual/upgrades_not_supported_for_arl.html
keywords: not supported, upgrades, internal disk drives, 7-mode
summary: Upgrades not supported for ARL
---

= Upgrades not supported for ARL
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You cannot perform the following upgrades:

*  To or from controllers that cannot run a version of ONTAP from ONTAP 9.0 to ONTAP 9.7.
+
For information on controller upgrades for systems running Data ONTAP operating in 7-Mode, refer to link:other_references.html[References] to link to the _NetApp Support Site_.

* To replacement controllers that do not support the disk shelves connected to the original controllers.
+
For disk-support information, refer to link:other_references.html[References] to link to the _Hardware Universe_.

* From controllers with root aggregates or data aggregates on internal drives.
+
If you want to upgrade controllers with root aggregates or data aggregates on internal disk drives, refer to link:other_references.html[References] to link to the _Controller Hardware Upgrade Express Guide_ and go to the procedure _Upgrading a pair of nodes running clustered Data ONTAP by moving volumes_.
+
NOTE: If you want to upgrade ONTAP on nodes in a cluster, refer to link:other_references.html[References] to link to the _ONTAP 9 Upgrade and Revert/Downgrade Guide_.
