---
sidebar: upgrade-arl-manual_sidebar
permalink: upgrade-arl-manual/upgrades_not_supported_for_arl.html
keywords: not supported, upgrades, internal disk drives, 7-mode
summary: Upgrades not supported for ARL
---

= Upgrades not supported for ARL
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You cannot perform the following upgrades:

*  To or from controllers that cannot run a version of ONTAP from ONTAP 9.0 to ONTAP 9.7.
+
Controller upgrades for systems running Data ONTAP operating in 7-Mode are available on the NetApp Support Site at mysupport.netapp.com.

* To replacement controllers that do not support the disk shelves connected to the original controllers.
+
See the _Hardware Universe_ at hwu.netapp.com for disk-support information.

* From controllers with root aggregates or data aggregates on internal drives.
+
If you want to upgrade controllers with root aggregates or data aggregates on internal disk drives, see the procedure "Upgrading a pair of nodes running clustered Data ONTAP by moving volumes" in _Controller Hardware Upgrade Express Guide_.
+
NOTE: If you want to upgrade ONTAP on nodes in a cluster, see the _ONTAP 9 Upgrade and Revert/Downgrade Guide_ at the ONTAP 9 Documentation Center.
