---
sidebar: upgrade-arl-auto-app_sidebar
permalink: upgrade-arl-auto-app/ensure_new_controllers_are_set_up_correctly.html
keywords: ensure, controllers, set up, ha, node3, node4, node2, lif, cluster, high, availability
summary: To ensure correct setup, you must enable the HA pair.
---

= Ensure that the new controllers are set up correctly
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-02 14:33:55.742436
//

[.lead]
include::../_include/ru_app_ensure_new_controllers_are_set_up_correctly_intro-step_12.adoc[]

[start=13]
. [[Step13]]Configure the SPs by using the following command on both nodes:
+
`system service-processor network modify -node <node_name>`
+
Refer to link:other_references.html[Other references] to link to the _System Administration Reference_ for information about the SPs and the _ONTAP 9.8 Commands: Manual Page Reference_ for detailed information about the system `service-processor network modify` command.

include::../_include/ru_app_ensure_new_controllers_are_set_up_correctly_step_13_15.adoc[]

.After you finish

If Storage Encryption is enabled on node3 and node4, complete the section link:set_up_storage_encryption_new_module.html[Set up Storage Encryption on the new controller module]. Otherwise, complete the section link:decommission_old_system.html[Decommission the old system].
// 11 DEC 2020, thomi, checked
