---
sidebar: upgrade-arl-auto-app_sidebar
permalink: upgrade-arl-auto-app/overview_of_the_arl_upgrade.html
keywords: overview, arl, upgrade, owner, controller, hardware
summary: Before you upgrade the nodes using ARL, you should understand how the procedure works.
---

= Overview of the ARL upgrade
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-02 14:33:53.808201
//

[.lead]
Before you upgrade the nodes using ARL, you should understand how the procedure works. In this document, the procedure is broken down into several stages.

During the procedure, you upgrade the original controller hardware with the replacement controller hardware, one controller at a time, taking advantage of the HA pair configuration to relocate the ownership of non-root aggregates. All non-root aggregates must undergo two relocations to reach their final destination, which is the correct upgraded node.

Each aggregate has a home owner and current owner. The home owner is the actual owner of the aggregate, and the current owner is the temporary owner.

[cols=2]
|===
| Stage | Steps

| Stage 1: Prepare for upgrade
a| Run prechecks to verify that the operation can be performed.

Aggregate ownership at the end of Stage 1:

* Node1 is the home owner and current owner of the node1 aggregates.
* Node2 is the home owner and current owner of the node2 aggregates.

|Stage 2: Relocate and retire node1
a|Move non-root aggregates from node1 to node2.
Move non-SAN data LIFs owned by node1 to node2.
Retire node1.
Prepare for netbooting (optional).

Aggregate ownership at the end of Stage 2:

* Node2 is the current owner of node1 aggregates.
* Node2 is the home owner and current owner of node2 aggregates.

|Stage 3: Install and boot node3
a|Install and boot node3.
Set the FC or (converged network adapter) CNA configuration.
Map ports from node1 to node3.
Verify node3 is successfully installed.
Move non-SAN data LIFs owned by node1 from node2 to node3.
Relocate non-root aggregates owned by node1 from node2 to node3.

Aggregate ownership at the end of Stage 3:

* Node3 is the home owner and current owner of node1 aggregates.
* Node2 is the home owner and current owner of node2 aggregates.

|Stage 4: Relocate and retire node2
a|Relocate non-root aggregates from node2 to node3.
Move non-SAN data LIFs owned by node2 to node 3.
Retire node2.

Aggregate ownership at the end of Stage 4:

* Node3 is the home owner and current owner of aggregates that originally belonged to node1.
* Node2 is the home owner of node2 aggregates.
* Node3 is the current owner of node2 aggregates.

|Stage 5: Install and boot node4
a|Install and boot node4.
Set the FC or CNA configuration on node4.
Map ports from node2 to node4.
Verify the node4 installation.
Relocate non-SAN data LIFs owned by node2 from node3 to node4 and verify the SAN LIFs on node4.

Aggregate ownership at the end of Stage 5:

* Node3 is the home owner and current owner of the aggregates that originally belonged to node1.
* Node4 is the home owner and current owner of aggregates that originally belonged to node2.

|Stage 6: Complete the upgrade
|Verify the system is set up correctly.
Set up Storage Encryption on the new controller module.
Resume NetApp SnapMirror operations if needed.
|===
