---
sidebar: upgrade-arl-auto-app_sidebar
permalink: upgrade-arl-auto-app/preparing_for_netboot.html
keywords: preparing, netboot, ndac, ontap
summary: After you physically rack node3 and node4 later in the procedure, you might need to netboot them.
---

= Preparing for netboot
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-02 14:33:54.096389
//

[.lead]
After you physically rack node3 and node4 later in the procedure, you might need to netboot them. The term `netboot` means you are booting from an ONTAP image stored on a remote server. When preparing for netboot, you must put a copy of the ONTAP 9 boot image onto a web server that the system can access.

==== Before you begin

* Verify that you can access a HTTP server with the system.
* You need to download the necessary system files for your platform and the correct version of ONTAP from the NetApp Support Site at link:mysupport.netapp.com[mysupport.netapp.com].

==== About this task

You must netboot the new controllers if they do not have the same version of ONTAP 9 installed on them that is installed on the original controllers. After you install each new controller, you boot the system from the ONTAP 9 image stored on the web server. You can then download the correct files to the boot media device for subsequent system boots.

However, you do not need to netboot the controllers if the same version of ONTAP 9 is installed on them that is installed on the original controllers. If so, you can skip this section and proceed to *xref* Stage 3 Installing and booting node3.

.Steps

. Access the NetApp Support Site to download the files used for performing the netboot of the system.
. Download the appropriate ONTAP software from the software download section of the NetApp Support Site and store the `<ontap_version>_image.tgz` file on a web-accessible directory.
. Change to the web-accessible directory and verify that the files you need are available.

|===
|For... |Then...

|FAS/AFF8000 series systems
|Extract the contents of the <ontap_version>_image.tgz file to the target directory by using the following command:
tar -zxvf <ontap_version>_image.tgz
 If you are extracting the contents on Windows, use 7-Zip or WinRAR to extract the netboot image.
Your directory listing should contain a netboot folder with a kernel file:
netboot/kernel

|Overriding destination checks
|Your directory listing should contain the following file:
<ontap_version>_image.tgz
You do not need to extract the contents of the
<ontap_version>_image.tgz file.

|===

You will use the information in the directories in Stage 3.
