---
sidebar: sidebar
permalink: upgrade-arl-auto-app/stage_5_install_and_boot_node4_overview.html
keywords: install, boot, node4, node2, node-management
summary: During Stage 5, you install and boot node4, map the cluster and node-management ports from node2 to node4.
---

= Stage 5. Install and boot node4
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-02 14:33:54.983598
//

[.lead]
During Stage 5, you install and boot node4, map the cluster and node-management ports from node2 to node4, and verify the node4 installation. You also move the NAS data LIFs owned by node2 from node3 to node4 and relocate node2's aggregates from node3 to node4.

.Steps

. link:installing_and_booting_node4.html[Install and boot node4]
. link:setting_the_fc_or_uta_uta2_configuration_on_node4.html[Set the FC or UTA/UTA2 configuration on node4]
. link:verifying_the_node4_installation.html[Verify the node4 installation]
. link:restoring_key-manager_configuration_on_node4.html[Restore key-manager configuration on node4]
. link:moving_non-root_aggregates_and_nas_data_lifs_owned_by_node2_from_node3_to_node4.html[Moe non-root aggregates and NAS data LIFs owned by node2 from node3 to node4]
// 10 D#C 2020, thomi, checked
