---
sidebar: upgrade-controller_sidebar
permalink: upgrade-controller/arl-auto-app_checking_for_aggregate_relocation_failure.html
keywords: test
summary: This is a test summary
---

= Checking for aggregate relocation failure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-02 14:33:55.839560
//

[.lead]
During the procedure, ARL might fail in Stage 2, Stage 3, or Stage 5.

*Steps*

. Enter the following command and examine its output:
+
`storage aggregate relocation show `
+
The `storage aggregate relocation show` command shows you which aggregates were successfully relocated and which ones were not, along with the causes of failure.

. Check the console for any EMS messages.
. Take one of the following actions:

** Take the appropriate corrective action, depending on the output of the `storage aggregate relocation show `command and the output of the EMS message.
** Force relocation of the aggregate or aggregates by using the `override-vetoes` option or the `override-destination-checks` option of the `storage aggregate relocation start` command.
+
For detailed information about the `storage aggregate relocation start, override- vetoes, `and` override-destination-checks` options, see the *ONTAP 9 Commands: Manual Page Reference.*
