---
sidebar: sidebar
permalink: arl-auto-app_setting_up_storage_encryption_on_the_new_controller_module.html
keywords:
summary:
---

= Setting up Storage Encryption on the new controller module
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-02 14:33:55.771144
//

[.lead]
If the replaced controller or the HA partner of the new controller uses Storage Encryption, you must configure the new controller module for Storage Encryption, including installing SSL certificates and setting up key management servers.

==== About this task

This procedure includes steps that are performed on the new controller module. You must enter the command on the correct node.

*Steps*

. Verify that the key management servers are still available, their status, and their authentication key information by using the following commands:
+
`security key-manager show -status `
+
`security key-manager query`

. Add the key management servers listed in the previous step to the key management server list in the new controller.
..  Add the key management server by using the following command:
+
`security key-manager -add <key_management_server_ip_address>`

.. Repeat the previous step for each listed key management server. You can link up to four key management servers.
.. Verify the that the key management servers were added successfully by using the following command:
+
`security key-manager show`

. On the new controller module, run the key management setup wizard to set up and install the key management servers.
+
You must install the same key management servers that are installed on the existing controller module.

.. Launch the key management server setup wizard on the new node by using the following command:
+
`security key-manager setup -node <new_controller_name>`

.. Complete the steps in the wizard to configure key management servers.
. Restore authentication keys from all linked key management servers to the new node by using the following command:
+
`security key-manager restore -node <new_controller_name>`


