---
sidebar: sidebar
permalink: arl-auto-app_issues_that_can_arise_in_multiple_stages_of_the_procedure.html
keywords: issues, arise, mutliple, stages, procedure, NDAC
summary: Some issues can occur during different stages of the procedure.
---

= Issues that can arise in multiple stages of the procedure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-02 14:33:55.906972
//

[.lead]
Some issues can occur during different stages of the procedure.

=== Unexpected storage failover show command output

During the procedure, if the node that hosts all data aggregates panics or is rebooted accidentally, you might see unexpected output for the `storage failover show` command before and after the reboot, panic, or power cycle.

==== About this task

You might see unexpected output from the `storage failover show` command in Stage 2, Stage 3, Stage 4, or Stage 5.

The following example shows the expected output of the `storage failover show` command if there are no reboots or panics on the node that hosts all the data aggregates:

....
cluster::> storage failover show
                                  Takeover
Node           Partner            PossibleState Description
-------------  -----------------  ---------  ----------------------------------------------
node 1         node 2             false      Unknown                                         node2          node1              false      Node owns partner aggregates as part of the non- disruptive head upgrade procedure. Takeover is not possible: Storage failover is disabled.

                                                                                          displayed.
....

The following example shows the output of the `storage failover show` command after a reboot or panic:

....
cluster::> storage failover show
                                  Takeover
Node         Partner    PossibleState Description
--------------  ------------- ---  -------- -------------------------------------
node1   node2         - Unknown
node2 node1    falseWaiting for node1, Partial giveback, Takeover
is not possible: Storage failover is disabled
2 entries were displayed.
....

Although the output says that a node is in partial giveback and that storage failover is disabled, you can disregard this message.

==== Step

No action is required; continue with the node-pair upgrade procedure.
