---
sidebar: sidebar
permalink: arl-auto-app_using_aggregate_relocation_to_upgrade_controller_hardware_overview.html
keywords: aggregate, relocation, upgrade, controller, hardware, ONTAP, non-root, ARL, HA
summary: You can nondisruptively upgrade the controller hardware on a pair of nodes running ONTAP 9.8.
---

= Using aggregate relocation to upgrade controller hardware
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-02 14:33:53.624503
//

[.lead]
You can nondisruptively upgrade the controller hardware on a pair of nodes running ONTAP 9.8 by migrating non-root aggregates from the original nodes to the new nodes in the same cluster. The data hosted on the nodes that are being upgraded is accessible during the upgrade.

==== About this task

This procedure uses a method called aggregate relocation (ARL), which takes advantage of the HA configuration to enable you to move ownership of non-root aggregates from one node to another if they share storage within the same cluster.

During the procedure, you upgrade the original controller hardware with the replacement controller hardware, relocating the ownership of non-root aggregates. You migrate aggregates multiple times from node to node to ensure that at least one node is serving data from the aggregates throughout the upgrade procedure. You also migrate data logical interfaces (LIFs) and assign the network ports on the new controller to the interface groups as you proceed.

[NOTE]
In this document, the original nodes are called *node1* and *node2*, and the new nodes are called *node3* and *node4*. During the described procedure, node1 is replaced by node3, and node2 is replaced by node4.

The terms *node1*, *node2*, *node3*, and *node4* are used only to distinguish between the original and new nodes. When following the procedure, you must substitute the real names of your original and new nodes. However, in reality, the names of the nodes do not change: node3 has the name node1, and node4 has the name node2 after the controller hardware is upgraded.

This document uses the term *systems with FlexArray Virtualization Software* to refer to systems that belong to these new platforms. It uses the term V-Series system to refer to the separate hardware systems that can attach to storage arrays

==== Important:

* This procedure is complex and assumes that you have advanced ONTAP administration skills. You also should read and understand the link:arl-auto-app_guidelines_for_upgrading_controllers_with_arl.html[Guidelines for upgrading controllers with ARL] and  link:arl-auto-app_overview_of_the_arl_upgrade.html[Overview of the ARL upgrade] sections before beginning the upgrade.
* This procedure assumes that the replacement controller hardware is new and has not been used. The steps required to prepare used controllers with the `wipeconfig` command are not included in this procedure. You must contact technical support if the replacement controller hardware was previously used, especially if the controllers were running Data ONTAP in 7- Mode.
* You can use this procedure to upgrade the controller hardware in clusters with more than two nodes; however, you need to perform the procedure separately for each high-availability (HA) pair in the cluster.
* This procedure applies to FAS systems, V-Series systems, AFF systems, and systems with FlexArray Virtualization Software. FAS systems released after ONTAP 9.5 can attach to storage arrays if the required license is installed. The existing V-Series systems are supported in ONTAP 9.5. See the V-Series Support Matrix at *Hardware Universe* at link:hwu.netapp.com[hwu.netapp.com] for information about the storage array and V-Series models.
* From ONTAP 9.6 this procedure applies to systems running 4-node NetApp MetroCluster configuration or higher. Since MetroCluster configuration sites can be at two physically different locations, the automated controller upgrade must be carried out individually at each MetroCluster site for an HA pair.
* If you are upgrading from an AFF A320 system, you can use volume moves to upgrade controller hardware or contact technical support. If you are willing to do volume moves, see the *Controller Hardware Upgrade Express Guide*.
