---
permalink: fas9000/controller-replace-system-config-restore-and-verify.html
sidebar: sidebar
keywords: aff a700, fas9000, verify, ha, state, controller, module, system, diagnostics
summary: "After completing the hardware replacement and booting to Maintenance mode, you verify the low-level system configuration of the replacement controller and reconfigure system settings as necessary."
---
= Restore and verify the system configuration - AFF A700 and FAS9000
:icons: font
:imagesdir: ../media/

[.lead]
After completing the hardware replacement and booting to Maintenance mode, you verify the low-level system configuration of the replacement controller and reconfigure system settings as necessary.

== Step 1: Set and verify system time after replacing the controller

include::../_include/set_time_after_controller_rep.adoc[]


== Step 2: Verify and set the HA state of the controller module

You must verify the `HA` state of the controller module and, if necessary, update the state to match your system configuration.

.Steps
. In Maintenance mode from the new controller module, verify that all components display the same `HA` state: `ha-config show`
+
The value for HA-state can be one of the following:

*** `ha`
*** `mcc`
*** `mcc-2n`
*** `mccip`
*** `non-ha`

 .. Confirm that the setting has changed: `ha-config show`

== Step 3: Run system-level diagnostics

[.lead]
You should run comprehensive or focused diagnostic tests for specific components and subsystems whenever you replace the controller.

All commands in the diagnostic procedures are issued from the node where the component is being replaced.

.Steps
. If the node to be serviced is not at the LOADER prompt, reboot the node: `halt`
+
After you issue the command, you should wait until the system stops at the LOADER prompt.

. At the LOADER prompt, access the special drivers specifically designed for system-level diagnostics to function properly: `boot_diags`
+
During the boot process, you can safely respond `y` to the prompts until the Maintenance mode prompt (*>) appears.

. Display and note the available devices on the controller module: `sldiag device show -dev mb`
+
The controller module devices and ports displayed can be any one or more of the following:

 ** `bootmedia` is the system booting device.
 ** `cna` is a Converged Network Adapter or interface not connected to a network or storage device.
 ** `fcal` is a Fibre Channel-Arbitrated Loop device not connected to a Fibre Channel network.
 ** `env` is motherboard environmentals.
 ** `mem` is system memory.
 ** `nic` is a network interface card.
 ** `nvram` is nonvolatile RAM.
 ** `nvmem` is a hybrid of NVRAM and system memory.
 ** `sas` is a Serial Attached SCSI device not connected to a disk shelf.

. Run diagnostics as desired.
+
[options="header" cols="1,2"]
|===
| If you want to run diagnostic tests on...| Then...
a|
Individual components
a|

 .. Clear the status logs: `sldiag device clearstatus`
 .. Display the available tests for the selected devices: `sldiag device show -dev __dev_name_`
+
`dev_name` can be any one of the ports and devices identified in the preceding step.

 .. Examine the output and, if applicable, select only the tests that you want to run: `sldiag device modify -dev _dev_name_ -selection only`
+
`-selection only` disables all other tests that you do not want to run for the device.

 .. Run the selected tests: `sldiag device run -dev _dev_name_`
+
After the test is complete, the following message is displayed:
+
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----

 .. Verify that no tests failed: `sldiag device status -dev _dev_name_ -long -state failed`
+
System-level diagnostics returns you to the prompt if there are no test failures, or lists the full status of failures resulting from testing the component.

a|
Multiple components at the same time
a|

 .. Review the enabled and disabled devices in the output from the preceding procedure and determine which ones you want to run concurrently.
 .. List the individual tests for the device: `sldiag device show -dev _dev_name_`
 .. Examine the output and, if applicable, select only the tests that you want to run: `sldiag device modify -dev _dev_name_ -selection only`
+
`-selection only` disables all other tests that you do not want to run for the device.

 .. Verify that the tests were modified: `sldiag device show`
 .. Repeat these substeps for each device that you want to run concurrently.
 .. Run diagnostics on all of the devices: `sldiag device run`
+
NOTE: Do not add to or modify your entries after you start running diagnostics.
+
After the test is complete, the following message is displayed:
+
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----

 .. Verify that there are no hardware problems on the node: `sldiag device status -long -state failed`
+
System-level diagnostics returns you to the prompt if there are no test failures, or lists the full status of failures resulting from testing the component.

|===

. Proceed based on the result of the preceding step:
+
[options="header" cols="1,2"]
|===
| If the system-level diagnostics tests...| Then...
a|
Were completed without any failures
a|

 .. Clear the status logs: `sldiag device clearstatus`
 .. Verify that the log was cleared: `sldiag device status`
+
The following default response is displayed:
+
----
SLDIAG: No log messages are present.
----

 .. Exit Maintenance mode: `halt`
+
The node displays the LOADER prompt.

 .. Boot the node from the LOADER prompt: `bye`
 .. Return the node to normal operation:

a|
An HA pair
a|
Perform a give back: `storage failover giveback -ofnode _replacement_node_name_`

NOTE: If you disabled automatic giveback, re-enable it with the `storage failover modify` command.

a|
A two-node MetroCluster configuration
a|
Proceed to the next step.

The MetroCluster switchback procedure is done in the next task in the replacement process.
a|
A stand-alone configuration
a|
Proceed to the next step.

No action is required.

You have completed system-level diagnostics.

a|
Resulted in some test failures
a|
Determine the cause of the problem:

 .. Exit Maintenance mode: `halt`
+
After you issue the command, wait until the system stops at the LOADER prompt.

 .. Turn off or leave on the power supplies, depending on how many controller modules are in the chassis:
  *** If you have two controller modules in the chassis, leave the power supplies turned on to provide power to the other controller module.
  *** If you have one controller module in the chassis, turn off the power supplies and unplug them from the power sources.
 .. Verify that you have observed all the considerations identified for running system-level diagnostics, that cables are securely connected, and that hardware components are properly installed in the storage system.
 .. Boot the controller module you are servicing, interrupting the boot by pressing `Ctrl-C` when prompted to get to the Boot menu:
  *** If you have two controller modules in the chassis, fully seat the controller module you are servicing in the chassis.
+
The controller module boots up when fully seated.

  *** If you have one controller module in the chassis, connect the power supplies, and then turn them on.
 .. Select Boot to maintenance mode from the menu.
 .. Exit Maintenance mode by entering the following command: `halt`
+
After you issue the command, wait until the system stops at the LOADER prompt.

 .. Rerun the system-level diagnostic test.

|===
