---
permalink: fas9000/x91148a-modules-with-open-slots-add.html
sidebar: sidebar
keywords: aff a700, fas9000, ass, x91148a, module, open, slots, nic, storage
summary: "You can add an X91148A module into an empty module slot in your system as either a 100GbE NIC or a storage module for the NS224 storage shelves."
---
= Add an X91148A module in an AFF A700 with open slots - AFF A700 and FAS9000
:icons: font
:imagesdir: ../media/

[.lead]
You can add an X91148A module into an empty module slot in your system as either a 100GbE NIC or a storage module for the NS224 storage shelves.

* Your system must be running ONTAP 9.8 and later.
* To non-disruptively add the X91148A module, you must takeover the target controller, remove the slot blanking cover in the target slot, add the module, and then giveback the target controller.
* There must be one or more open slots available on your system.
* If multiple slots are available, install the module according to the slot priority matrix for the X91148A module in the Hardware Universe.
+
https://hwu.netapp.com[NetApp Hardware Universe]

* If you are adding the X91148A module as a storage module, you must install the module slots 3 and/or 7.
* If you are adding the X91148A module as a 100GbE NIC, you can use any open slot. However, by default, slots 3 and 7 are set as storage slots. If you wish to use those slots as network slots and will not add NS224 shelves, you must modify the slots for networking use with the storage port modify -node <node name> -port <port name> -mode network command. See the Hardware Universe for other slots that can be used by the X91148A module for networking.
+
https://hwu.netapp.com[NetApp Hardware Universe]

* All other components in the system must be functioning properly; if not, you must contact technical support.

== Option 1: Add an X91148A module as a NIC module in a system with open slots

[.lead]
To add an X91148A module as a NIC module in a system with open slots, you must follow the specific sequence of steps.

.Steps
. Shutdown controller A:
 .. Disable automatic giveback: `storage failover modify -node local -auto-giveback false`
 .. Take over the target node: `storage failover takeover -ofnode target_node_name`
+
The console connection shows that the node drops to the LOADER prompt when the takeover is complete.
. If you are not already grounded, properly ground yourself.
. Remove the target slot blanking cover:
 .. Depress the lettered and numbered cam button.
 .. Rotate the cam latch down until it is in a horizontal position.
 .. Remove the blanking cover.
. Install the X91148A module:
 .. Align the X91148A module with the edges of the slot.
 .. Slide the X91148A module into the slot until the lettered and numbered I/O cam latch begins to engage with the I/O cam pin.
 .. Push the I/O cam latch all the way up to lock the module in place.
. Cable the module to the data switches.
. Reboot controller A. `boot_ontap`
. Giveback the node from the partner node. `storage failover giveback -ofnode target_node_name`
. Enable automatic giveback if it was disabled: `storage failover modify -node local -auto-giveback true`
. If you are using slots 3 and/or 7 for networking, use the storage port modify -node <node name> -port <port name> -mode network command to convert the slot for networking use.
. Repeat these steps for controller B.

== Option 2: Add an X91148A module as a storage module in a system with open slots

[.lead]
To add an X91148A module as a storage module in a system with open slots, you must follow the specific sequence of steps.

* This procedure presumes slots 3 and/or 7 are open.

.Steps
. Shut down controller A:
 .. Disable automatic giveback: `storage failover modify -node local -auto-giveback false`
 .. Take over the target node: `storage failover takeover -ofnode target_node_name`
+
The console connection shows that the node drops to the LOADER prompt when the takeover is complete.
. If you are not already grounded, properly ground yourself.
. Remove the target slot blanking cover:
 .. Depress the lettered and numbered cam button.
 .. Rotate the cam latch down until it is in a horizontal position.
 .. Remove the blanking cover.
. Install the X91148A module into slot 3:
 .. Align the X91148A module with the edges of the slot.
 .. Slide the X91148A module into the slot until the lettered and numbered I/O cam latch begins to engage with the I/O cam pin.
 .. Push the I/O cam latch all the way up to lock the module in place.
 .. If you are installing a second X91148A module for storage, repeat this step for the module in slot 7.
. Reboot controller A. `boot_ontap`
. Giveback the node from the partner node. `storage failover giveback -ofnode target_node_name`
. Enable automatic giveback if it was disabled: `storage failover modify -node local -auto-giveback true`
. Repeat these steps for controller B.
. Install and cable your NS224 shelves, as described in https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-nvme-hotadd/GUID-B215753F-F3E6-4FA0-A1E1-B9390B19AD94.html[Hot-adding an NS224 drive shelf].
