---
sidebar: upgrade-arl-manual-app_sidebar
permalink: upgrade-arl-manual-app/check_configure_uta_uta2_ports_node4.html
summary: If node4 has onboard UTA/UTA2 ports or a UTA/UTA2A card, you must check the configuration of the ports.
---

= Check and configure UTA/UTA2 ports on node4
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
include::../_include/ru_check_config_UTA_node4_intro_to_step2.adoc[]

. Examine the output of the `system node hardware unified-connect show` or `ucadmin show` command and determine whether the UTA/UTA2 ports have the personality you want.

. Take one of the following actions:
+
|===
|If the CNA ports... |Then...

|Do not have the personality that you want
|Go to <<Step5,Step 5>>.
|Have the personality that you want
|Skip Step 5 through Step 12 and go to <<Step13,Step 13>>.
|===

. [[Step5]]Take one of the following actions:
+
|===
|If the system... |Then...

|Has storage disks and is running Data ONTAP 8.3
|Boot node4 and enter maintenance mode by entering the following command:
`boot_ontap maint`
|Is a V-Series system or has FlexArray Virtualization Software and is connected to storage arrays
|Go to <<Step,Step 6>>.
You should already be in Maintenance mode.
|===

. [[Step6]]Take one of the following actions:
+
|===
|If you are configuring... |Then...

|Ports on a UTA/UTA2A card
|Go to <<Step7,Step 7>>.
|Onboard UTA/UTA2 ports
|Skip Step 7 and go to <<Step8,Step 8>>.
|===

. If the adapter is in initiator mode, and if the UTA/UTA2 port is online, take the UTA/UTA2 port offline by entering the following command:
+
`storage disable adapter <adapter_name>`
+
Adapters in target mode are automatically offline in Maintenance mode.

. If the current configuration does not match the desired use, enter the following command to change the configuration as needed:
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`
+
* `-m` is the personality mode: FC or 10GbE UTA.
* `-t` is the FC4 type: target or initiator.

+
NOTE: You need to use FC initiator for tape drives and FlexArray Virtualization systems. You need to use the FC target for SAN clients.

. [[Step7]]Verify the settings by entering the following command and examining its output:
+
`ucadmin show`

. [[Step8]]Perform one of the following actions:
+
|===
|If the system... |Then...

|Has storage disks a|
.. Enter the following command:
`halt`
The system stops at the boot environment prompt.
.. Enter the following command:
`boot_ontap`
|Is a V-Series system or has FlexArray Virtualization Software and is connected to storage arrays and is running Data ONTAP 8.3
|Reboot to Maintenance mode by entering the following command:
`boot_ontap maint`
|===

. Verify the settings by entering one of the following commands:
+
|===
|If the system... |Then...

|Has storage disks
|Enter the following command:
`system node hardware unified-connect show`
|Is a V-Series system or has FlexArray Virtualization Software and is connected to storage arrays
|Enter the following command:
`ucadmin show`
|===
+
The output in the following examples shows that the FC4 type of adapter 1b is changing to `initiator` and that the mode of adapters 2a and 2b is changing to `cna`.
+
----
cluster1::> system node hardware unified-connect show
               Current  Current   Pending  Pending    Admin
Node  Adapter  Mode     Type      Mode     Type       Status
----  -------  -------  --------- -------  -------    -----
f-a    1a      fc       initiator -        -          online
f-a    1b      fc       target    -        initiator  online
f-a    2a      fc       target    cna      -          online
f-a    2b      fc       target    cna      -          online
4 entries were displayed.
----
+
----
*> ucadmin show
               Current Current   Pending  Pending    Admin
Node  Adapter  Mode    Type      Mode     Type       Status
----  -------  ------- --------- -------  -------    -----
f-a    1a      fc      initiator -        -          online
f-a    1b      fc      target    -        initiator  online
f-a    2a      fc      target    cna      -          online
f-a    2b      fc      target    cna      -          online
4 entries were displayed.
*>
----

. Place any target ports online by entering one of the following commands, once for each port:
+
|===
|If the system... |Then...

|Has storage disks |`network fcp adapter modify -node <node_name> -adapter <adapter_name> -state up`
|Is a V-Series system or has FlexArray Virtualization Software and is connected to storage arrays
|`fcp config <adapter_name> up`
|===

. [[Step13]]Cable the port.

. Perform one of the following actions:
+
|===
|If the system... |Then...

|Has storage disks |Go to  link:map_ports_node2_node4.html[Map ports from node2 to node4].
|Is a V-Series system or has FlexArray Virtualization Software and is connected to storage arrays
|Return to link:install_boot_node4.html[Install and boot node4], and resume the section at Step 9.
|===
