---
sidebar: upgrade-arl-manual-app_sidebar
permalink: upgrade-arl-manual-app/set_fc_uta_uta2_config_node4.html
summary: If node4 has onboard FC ports, onboard unified target adapter (UTA/UTA2) ports, or a UTA/UTA2 card.
---

= Set the FC or UTA/UTA2 configuration on node4
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If node4 has onboard FC ports, onboard unified target adapter (UTA/UTA2) ports, or a UTA/UTA2 card, you must configure the settings before completing the rest of the procedure.

.About this task

You might need to complete link:config_fc_ports_node4.html[Configure FC ports on node4], the link:check_configure_uta_uta2_ports_node4.html[Check and configure UTA/UTA2 ports on node4], or both sections.

If node4 does not have onboard FC ports, onboard UTA/UTA2 ports, or a UTA/UTA2 card, and you are upgrading a system with storage disks, you can skip to link:map_ports_node2_node4.html[Map ports from node2 to node4].
However, if you have a V-Series system or have FlexArray Virtualization Software and are connected to storage arrays, and node4 does not have onboard FC ports, onboard UTA/ UTA2 ports, or a UTA/UTA2 card, you must return to the link:install_boot_node4.html[Install and boot node4] section and resume at Step 9. Make sure that node4 has sufficient rack space. If node4 is in a separate chassis from node2, you can put node4 in the same location as node3. If node2 and node4 are in the same chassis, then node4 is already in its appropriate rack location.

.Choices

* link:config_fc_ports_node4.html[Configure FC ports on node4]
* link:check_configure_uta_uta2_ports_node4.html[Check and configure UTA/UTA2 ports on node4]
