---
sidebar: upgrade-arl-manual-app_sidebar
permalink: upgrade-arl-manual-app/supported_upgrades_for_arl.html
summary:
---

= Supported upgrades for ARL
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can upgrade a pair of nodes using ARL under the following circumstances:


* Both the original controllers and the replacement controllers must be running the same version of ONTAP 9.8 or later before the upgrade.

* The replacement controllers must have equal or higher capacity than the original controllers. Equal or higher capacity refers to attributes, such as the NVRAM size, volume, LUN, or aggregate count limits; it also refers to the maximum volume or aggregate sizes of the new nodes.

* You can upgrade the following type of systems:
** A FAS system to a FAS system.
** A FAS system to a V-Series system or a system with FlexArray Virtualization Software.
** A V-Series system to a V-Series system or a system with FlexArray Virtualization Software.
** A V-Series system or a system with FlexArray Virtualization Software to a FAS system, provided that the V-Series system or system with FlexArray Virtualization Software has no array LUNs.
** An AFF system to an AFF system.

* Controller upgrade using ARL is supported on systems configured with SnapLock Enterprise
and SnapLock Compliance volumes.

You should verify whether the ARL can be performed on the original and replacement controllers. You should check the size of all defined aggregates and number of disks supported by the original system. Then compare them with the aggregate size and number of disks supported by the new system. This information is available in the Hardware Universe at hwu.netapp.com. The aggregate size and the number of disks supported by the new system must be equal to or greater than the aggregate size and number of disks supported by the original system.

You should validate in the cluster mixing rules whether new nodes can become part of the cluster with the existing nodes when the original controller is replaced. For more information about cluster mixing rules, see the Hardware Universe at hwu.netapp.com.

NOTE: Both systems are either high-availability (HA) or non-HA. Both nodes must either have the personality enabled or disabled; you cannot combine a node with the All Flash Optimized personality enabled with a node that does not have the personality enabled in the same HA pair. If the personalities are different, contact technical support.
