---
sidebar: greeley_sidebar
permalink: greeley/9336c_migrate_from_a_switched_cluster_with_sat_storage_by_reusing_the_storage_switches.html
keywords:
summary:
---

= Migrate from a switched cluster with SAT storage by reusing the storage switches
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-04-29 11:40:03.890730
//

==== Migrate the storage switches

By reusing the storage switches the storage switches of HA pair 1 become the shared switches.

*Steps*

. Verify that the storage configuration of HA pair 1 (and HA pair 2) is correct and error free:

----
system switch ethernet show, storage port show -port-type ENET
----

. Move the HA pair 1, NSM224 path A cables from storage switch A to the Greeley NS224 storage ports for HA pair 1, path A on storage switch A.
. Move the cable from HA pair 1, node A, path A to the Greeley storage port for HA pair 1, node A on storage switch A.
. Move the cable from HA pair 1, node B, path A to the Greeley storage port for HA pair 1, node B on storage switch A.
. Verify the storage attached to HA pair 1, storage switch A is healthy:

----
system health alert show -instance
----

. Replace the storage RCF on shared switch A with the shared RCF file. [LINK to the install RCF doc]
. Verify the storage attached to HA pair 1, storage switch A is healthy:

----
system health alert show -instance
----

. Move the HA pair 1, NSM224 path B cables from storage switch B to the shared NS224 storage ports for HA pair 1, path B to storage switch B.
. Move the cable from HA pair 1, node A, path B to the shared storage port for HA pair 1, node A, path B on storage switch B.
. Move the cable from HA pair 1, node B, path B to the shared storage port for HA pair 1, node B, path B on storage switch B.
. Verify the storage attached to HA pair 1, storage switch B is healthy:

----
system health alert show -instance
----

. Replace the storage RCF file on shared switch B with the shared RCF file. [LINK to the install RCF doc]
. Verify the storage attached to HA pair 1, storage switch B is healthy:

----
system health alert show -instance
----

. Verify the storage configuration of HA pair 1 is correct and error free:

----
system switch ethernet show, storage port show -port-type ENET
----

. Skip to step 50 if this is a 2N config, else continue to next step.
. Verify that the storage configuration of HA pair 2 is correct and error free:

----
system switch ethernet show, storage port show -port-type ENET
----

. Move the HA pair 2, NSM224 path A cables from storage switch A to the shared NS224 storage ports for HA pair 2, path A on shared switch A.
. Move the cable from HA pair 2, node A, path A to the shared storage port for HA pair 2, node A on shared switch A.
. Move the cable from HA pair 2, node B, path A to the shared storage port for HA pair 2, node B on shared switch A.
. Verify the storage attached to HA pair 2, shared switch A is healthy:

----
system health alert show -instance
----

. Move the HA pair 2, NSM224 path B cables from storage switch B to the shared NS224 storage ports for HA pair 2, path B to shared switch B.
. Move the cable from HA pair 2, node A, path B to the Greeley storage port for HA pair 2, node A, path B on shared switch B.
. Move the cable from HA pair 2, node B, path B to the Greeley storage port for HA pair 2, node B, path B on shared switch B.
. Verify the storage attached to HA pair 2, shared switch B is healthy: `system health alert show -instance`

. Verify the storage configuration of HA pair 2 is correct and error free: `system switch ethernet show`, `storage port show -port-type ENET`

. Install the ISLs between shared switch A and shared switch B:

----
sh1# configure
Enter configuration commands, one per line. End with CNTL/Z.
sh1 (config)# interface e1/35-36
sh1 (config-if-range)# no lldp transmit
sh1 (config-if-range)# no lldp receive
sh1 (config-if-range)# switchport mode trunk
sh1 (config-if-range)# no spanning-tree bpduguard enable
sh1 (config-if-range)# channel-group 101 mode active
sh1 (config-if-range)# exit
sh1 (config)# interface port-channel 101
sh1 (config-if)# switchport mode trunk
sh1 (config-if)# spanning-tree port type network
sh1 (config-if)# exit
sh1 (config)# exit
----

. Migrate the cluster networking from the existing cluster switches to the shared switches using the switch replacement procedure and the shared RCF. The new shared switch A is "cs1". The new shared switch B is "cs2". [LINK to the install RCF doc]
. Verify that the switched networking config is valid: `network port show`

. Remove the unused cluster switches.
. Remove the unused storage switches.
